using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Linq;
using Avalonia.Collections;
using Avalonia.Controls;
using Avalonia.Headless.XUnit;
using Xunit;

namespace Avalonia.Controls.DataGridTests;

public class DataGridDiagnosticsTests
{
    [AvaloniaFact]
    public void DataGrid_Emits_Activities_And_Metrics()
    {
        var items = CreateItems(120);
        using var listener = new DiagnosticsListener();

        var grid = CreateAutoGrid(items);
        ExerciseGrid(grid, items);

        AssertActivity(listener, "ProDataGrid.DataGrid.RefreshRowsAndColumns",
            DataGridDiagnostics.Tags.ClearRows,
            DataGridDiagnostics.Tags.AutoGenerateColumns,
            DataGridDiagnostics.Tags.Columns,
            DataGridDiagnostics.Tags.Rows,
            DataGridDiagnostics.Tags.SlotCount);
        AssertActivity(listener, "ProDataGrid.DataGrid.RefreshRows",
            DataGridDiagnostics.Tags.ClearRows,
            DataGridDiagnostics.Tags.RecycleRows,
            DataGridDiagnostics.Tags.Columns,
            DataGridDiagnostics.Tags.Rows,
            DataGridDiagnostics.Tags.SlotCount);
        AssertActivity(listener, "ProDataGrid.DataGrid.UpdateDisplayedRows",
            DataGridDiagnostics.Tags.DisplayHeight,
            DataGridDiagnostics.Tags.SlotCount,
            DataGridDiagnostics.Tags.Columns);
        AssertActivity(listener, "ProDataGrid.DataGrid.GenerateRow",
            DataGridDiagnostics.Tags.RowIndex,
            DataGridDiagnostics.Tags.Slot,
            DataGridDiagnostics.Tags.Source);
        AssertActivity(listener, "ProDataGrid.DataGrid.AutoGenerateColumns",
            DataGridDiagnostics.Tags.Columns,
            DataGridDiagnostics.Tags.AutoGeneratedColumns);
        AssertActivity(listener, "ProDataGrid.DataGrid.SelectionChanged",
            DataGridDiagnostics.Tags.AddedCount,
            DataGridDiagnostics.Tags.RemovedCount,
            DataGridDiagnostics.Tags.SelectionSource,
            DataGridDiagnostics.Tags.UserInitiated);

        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.DataGridRefreshTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.RowsRefreshTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.RowsDisplayUpdateTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.RowGenerateTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.ColumnsAutoGenerateTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.SelectionChangedTimeName);

        AssertHasLongMeasurement(listener, DataGridDiagnostics.Meters.RowsRealizedCountName);
        AssertHasLongMeasurement(listener, DataGridDiagnostics.Meters.RowsRecycledCountName);
        AssertHasLongMeasurement(listener, DataGridDiagnostics.Meters.RowsPreparedCountName);
        AssertHasLongMeasurement(listener, DataGridDiagnostics.Meters.ColumnsAutoGeneratedCountName);
        AssertHasLongMeasurement(listener, DataGridDiagnostics.Meters.SelectionChangedCountName);

        AssertMeasurementTag(listener, DataGridDiagnostics.Meters.RowsRealizedCountName, DataGridDiagnostics.Tags.Source);
        AssertMeasurementTag(listener, DataGridDiagnostics.Meters.SelectionChangedCountName, DataGridDiagnostics.Tags.SelectionSource);
    }

    [Fact]
    public void CollectionView_Emits_Activities_And_Metrics()
    {
        var items = CreateItems(40);
        using var listener = new DiagnosticsListener();

        ExerciseCollectionViews(items);

        AssertActivity(listener, "ProDataGrid.CollectionView.Refresh",
            DataGridDiagnostics.Tags.UsesLocalArray,
            DataGridDiagnostics.Tags.FilterEnabled,
            DataGridDiagnostics.Tags.SortDescriptions,
            DataGridDiagnostics.Tags.GroupDescriptions,
            DataGridDiagnostics.Tags.PageSize,
            DataGridDiagnostics.Tags.PageIndex,
            DataGridDiagnostics.Tags.IsGrouping);
        AssertActivity(listener, "ProDataGrid.CollectionView.Filter",
            DataGridDiagnostics.Tags.FilterEnabled,
            DataGridDiagnostics.Tags.SortDescriptions);
        AssertActivity(listener, "ProDataGrid.CollectionView.Sort",
            DataGridDiagnostics.Tags.SortDescriptions,
            DataGridDiagnostics.Tags.Rows);
        AssertActivity(listener, "ProDataGrid.CollectionView.Group",
            DataGridDiagnostics.Tags.GroupDescriptions,
            DataGridDiagnostics.Tags.Rows);
        AssertActivity(listener, "ProDataGrid.CollectionView.GroupTemporary",
            DataGridDiagnostics.Tags.GroupDescriptions,
            DataGridDiagnostics.Tags.Rows);
        AssertActivity(listener, "ProDataGrid.CollectionView.GroupPage",
            DataGridDiagnostics.Tags.GroupDescriptions,
            DataGridDiagnostics.Tags.PageSize,
            DataGridDiagnostics.Tags.PageIndex);

        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.CollectionRefreshTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.CollectionFilterTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.CollectionSortTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.CollectionGroupTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.CollectionGroupTemporaryTimeName);
        AssertHasDoubleMeasurement(listener, DataGridDiagnostics.Meters.CollectionGroupPageTimeName);
    }

    [AvaloniaFact]
    public void DataGrid_Activities_Report_Valid_Tag_Values()
    {
        var items = CreateItems(100);
        using var listener = new DiagnosticsListener();

        var grid = CreateAutoGrid(items);
        ExerciseGrid(grid, items);

        var refresh = GetActivity(listener, "ProDataGrid.DataGrid.RefreshRowsAndColumns");
        var refreshTags = GetTagMap(refresh);
        AssertTagBool(refreshTags, DataGridDiagnostics.Tags.ClearRows);
        AssertTagBool(refreshTags, DataGridDiagnostics.Tags.AutoGenerateColumns);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.Columns, min: 0);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.Rows, min: 0);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.SlotCount, min: 0);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.FirstDisplayedSlot, min: -1);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.LastDisplayedSlot, min: -1);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.DisplayedSlots, min: 0);

        var display = GetActivity(listener, "ProDataGrid.DataGrid.UpdateDisplayedRows");
        var displayTags = GetTagMap(display);
        AssertTagDouble(displayTags, DataGridDiagnostics.Tags.DisplayHeight, min: 0);
        AssertTagInt(displayTags, DataGridDiagnostics.Tags.SlotCount, min: 0);
        AssertTagInt(displayTags, DataGridDiagnostics.Tags.Columns, min: 0);

        var generate = GetActivity(listener, "ProDataGrid.DataGrid.GenerateRow");
        var generateTags = GetTagMap(generate);
        AssertTagInt(generateTags, DataGridDiagnostics.Tags.RowIndex, min: 0);
        AssertTagInt(generateTags, DataGridDiagnostics.Tags.Slot, min: 0);
        var source = AssertTagString(generateTags, DataGridDiagnostics.Tags.Source);
        Assert.Contains(source, new[]
        {
            DataGridDiagnostics.Sources.Existing,
            DataGridDiagnostics.Sources.New,
            DataGridDiagnostics.Sources.Recycled,
            DataGridDiagnostics.Sources.OwnContainer,
        });

        var autogen = GetActivity(listener, "ProDataGrid.DataGrid.AutoGenerateColumns");
        var autogenTags = GetTagMap(autogen);
        AssertTagInt(autogenTags, DataGridDiagnostics.Tags.Columns, min: 0);
        AssertTagInt(autogenTags, DataGridDiagnostics.Tags.AutoGeneratedColumns, min: 0);

        var selection = GetActivity(listener, "ProDataGrid.DataGrid.SelectionChanged");
        var selectionTags = GetTagMap(selection);
        AssertTagInt(selectionTags, DataGridDiagnostics.Tags.AddedCount, min: 0);
        AssertTagInt(selectionTags, DataGridDiagnostics.Tags.RemovedCount, min: 0);
        AssertTagString(selectionTags, DataGridDiagnostics.Tags.SelectionSource);
        AssertTagBool(selectionTags, DataGridDiagnostics.Tags.UserInitiated);
    }

    [AvaloniaFact]
    public void CollectionView_Activities_Report_Valid_Tag_Values()
    {
        var items = CreateItems(60);
        using var listener = new DiagnosticsListener();

        ExerciseCollectionViews(items);

        var refresh = GetActivity(listener, "ProDataGrid.CollectionView.Refresh");
        var refreshTags = GetTagMap(refresh);
        AssertTagBool(refreshTags, DataGridDiagnostics.Tags.UsesLocalArray);
        AssertTagBool(refreshTags, DataGridDiagnostics.Tags.FilterEnabled);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.SortDescriptions, min: 0);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.GroupDescriptions, min: 0);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.PageSize, min: 0);
        AssertTagInt(refreshTags, DataGridDiagnostics.Tags.PageIndex, min: 0);
        AssertTagBool(refreshTags, DataGridDiagnostics.Tags.IsGrouping);

        var filter = GetActivity(listener, "ProDataGrid.CollectionView.Filter");
        var filterTags = GetTagMap(filter);
        AssertTagBool(filterTags, DataGridDiagnostics.Tags.FilterEnabled);
        AssertTagInt(filterTags, DataGridDiagnostics.Tags.SortDescriptions, min: 0);

        var sort = GetActivity(listener, "ProDataGrid.CollectionView.Sort");
        var sortTags = GetTagMap(sort);
        AssertTagInt(sortTags, DataGridDiagnostics.Tags.SortDescriptions, min: 1);
        AssertTagInt(sortTags, DataGridDiagnostics.Tags.Rows, min: 1);

        var group = GetActivity(listener, "ProDataGrid.CollectionView.Group");
        var groupTags = GetTagMap(group);
        AssertTagInt(groupTags, DataGridDiagnostics.Tags.GroupDescriptions, min: 1);
        AssertTagInt(groupTags, DataGridDiagnostics.Tags.Rows, min: 1);

        var groupTemp = GetActivity(listener, "ProDataGrid.CollectionView.GroupTemporary");
        var groupTempTags = GetTagMap(groupTemp);
        AssertTagInt(groupTempTags, DataGridDiagnostics.Tags.GroupDescriptions, min: 1);
        AssertTagInt(groupTempTags, DataGridDiagnostics.Tags.Rows, min: 1);

        var groupPage = GetActivity(listener, "ProDataGrid.CollectionView.GroupPage");
        var groupPageTags = GetTagMap(groupPage);
        AssertTagInt(groupPageTags, DataGridDiagnostics.Tags.GroupDescriptions, min: 1);
        AssertTagInt(groupPageTags, DataGridDiagnostics.Tags.PageSize, min: 1);
        AssertTagInt(groupPageTags, DataGridDiagnostics.Tags.PageIndex, min: 0);
    }

    [AvaloniaFact]
    public void DataGrid_Metrics_Report_Valid_Durations()
    {
        var items = CreateItems(200);
        using var listener = new DiagnosticsListener();

        var grid = CreateAutoGrid(items);
        ExerciseGrid(grid, items);

        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.DataGridRefreshTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.RowsRefreshTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.RowsDisplayUpdateTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.RowGenerateTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.ColumnsAutoGenerateTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.SelectionChangedTimeName);
    }

    [AvaloniaFact]
    public void DataGrid_Metrics_Report_Valid_Counters()
    {
        var items = CreateItems(200);
        using var listener = new DiagnosticsListener();

        var grid = CreateAutoGrid(items);
        ExerciseGrid(grid, items);

        AssertValidLongMeasurements(listener, DataGridDiagnostics.Meters.RowsRealizedCountName);
        AssertValidLongMeasurements(listener, DataGridDiagnostics.Meters.RowsRecycledCountName);
        AssertValidLongMeasurements(listener, DataGridDiagnostics.Meters.RowsPreparedCountName);
        AssertValidLongMeasurements(listener, DataGridDiagnostics.Meters.ColumnsAutoGeneratedCountName);
        AssertValidLongMeasurements(listener, DataGridDiagnostics.Meters.SelectionChangedCountName);
    }

    [AvaloniaFact]
    public void CollectionView_Metrics_Report_Valid_Durations()
    {
        var items = CreateItems(200);
        using var listener = new DiagnosticsListener();

        ExerciseCollectionViews(items);

        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.CollectionRefreshTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.CollectionFilterTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.CollectionSortTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.CollectionGroupTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.CollectionGroupTemporaryTimeName);
        AssertValidDoubleMeasurements(listener, DataGridDiagnostics.Meters.CollectionGroupPageTimeName);
    }

    private static DataGrid CreateAutoGrid(IList<TestItem> items)
    {
        var root = new Window
        {
            Width = 320,
            Height = 200,
        };

        root.SetThemeStyles();

        var grid = new DataGrid
        {
            AutoGenerateColumns = true,
            ItemsSource = items,
            UseLogicalScrollable = true,
        };

        root.Content = grid;
        root.Show();
        return grid;
    }

    private static List<TestItem> CreateItems(int count)
    {
        var items = new List<TestItem>(count);
        for (var i = 0; i < count; i++)
        {
            items.Add(new TestItem($"Item {i}", i % 2 == 0 ? "Even" : "Odd", i));
        }

        return items;
    }

    private static Activity AssertActivity(DiagnosticsListener listener, string name, params string[] tags)
    {
        var activity = GetActivity(listener, name);

        var tagKeys = activity.TagObjects.Select(tag => tag.Key).ToHashSet(StringComparer.Ordinal);
        foreach (var tag in tags)
        {
            Assert.Contains(tag, tagKeys);
        }

        return activity;
    }

    private static Activity GetActivity(DiagnosticsListener listener, string name)
    {
        var activity = listener.Activities.LastOrDefault(a => a.OperationName == name);
        Assert.NotNull(activity);
        return activity!;
    }

    private static IReadOnlyDictionary<string, object?> GetTagMap(Activity activity)
    {
        return activity.TagObjects.ToDictionary(tag => tag.Key, tag => tag.Value, StringComparer.Ordinal);
    }

    private static void AssertHasDoubleMeasurement(DiagnosticsListener listener, string instrumentName)
    {
        Assert.True(listener.DoubleMeasurements.TryGetValue(instrumentName, out var values) && values.Count > 0,
            $"Expected measurements for {instrumentName}.");
    }

    private static void AssertHasLongMeasurement(DiagnosticsListener listener, string instrumentName)
    {
        Assert.True(listener.LongMeasurements.TryGetValue(instrumentName, out var values) && values.Count > 0,
            $"Expected measurements for {instrumentName}.");
    }

    private static void AssertMeasurementTag(DiagnosticsListener listener, string instrumentName, string tagKey)
    {
        Assert.True(listener.LongMeasurementTags.TryGetValue(instrumentName, out var entries) &&
                    entries.Any(entry => entry.ContainsKey(tagKey)),
            $"Expected tag '{tagKey}' for {instrumentName}.");
    }

    private static void AssertValidDoubleMeasurements(DiagnosticsListener listener, string instrumentName)
    {
        Assert.True(listener.DoubleMeasurements.TryGetValue(instrumentName, out var values) && values.Count > 0,
            $"Expected measurements for {instrumentName}.");
        Assert.All(values, value =>
        {
            Assert.False(double.IsNaN(value), $"Measurement for {instrumentName} is NaN.");
            Assert.False(double.IsInfinity(value), $"Measurement for {instrumentName} is infinite.");
            Assert.True(value >= 0, $"Measurement for {instrumentName} should be non-negative.");
        });
        Assert.Contains(values, value => value > 0);
    }

    private static void AssertValidLongMeasurements(DiagnosticsListener listener, string instrumentName)
    {
        Assert.True(listener.LongMeasurements.TryGetValue(instrumentName, out var values) && values.Count > 0,
            $"Expected measurements for {instrumentName}.");
        Assert.All(values, value => Assert.True(value >= 0, $"Measurement for {instrumentName} should be non-negative."));
        Assert.Contains(values, value => value > 0);
    }

    private static void AssertTagBool(IReadOnlyDictionary<string, object?> tags, string key)
    {
        Assert.True(tags.TryGetValue(key, out var value), $"Missing tag '{key}'.");
        Assert.IsType<bool>(value);
    }

    private static void AssertTagInt(IReadOnlyDictionary<string, object?> tags, string key, int min)
    {
        Assert.True(tags.TryGetValue(key, out var value), $"Missing tag '{key}'.");
        var typed = Assert.IsType<int>(value);
        Assert.True(typed >= min, $"Tag '{key}' should be >= {min}.");
    }

    private static void AssertTagDouble(IReadOnlyDictionary<string, object?> tags, string key, double min)
    {
        Assert.True(tags.TryGetValue(key, out var value), $"Missing tag '{key}'.");
        var typed = Assert.IsType<double>(value);
        Assert.True(typed >= min, $"Tag '{key}' should be >= {min}.");
    }

    private static string AssertTagString(IReadOnlyDictionary<string, object?> tags, string key)
    {
        Assert.True(tags.TryGetValue(key, out var value), $"Missing tag '{key}'.");
        var typed = Assert.IsType<string>(value);
        Assert.False(string.IsNullOrWhiteSpace(typed), $"Tag '{key}' should be non-empty.");
        return typed;
    }

    private static void ExerciseGrid(DataGrid grid, IList<TestItem> items)
    {
        grid.UpdateLayout();
        grid.SelectedIndex = 1;
        grid.UpdateLayout();

        var firstColumn = grid.Columns[0];
        var targetIndex = Math.Min(items.Count - 1, 80);
        grid.ScrollIntoView(items[targetIndex], firstColumn);
        grid.UpdateLayout();
        grid.ScrollIntoView(items[0], firstColumn);
        grid.UpdateLayout();
        grid.RefreshRows(recycleRows: true, clearRows: true);
        grid.UpdateLayout();

        var refreshedItems = CreateItems(Math.Max(10, items.Count / 2));
        grid.ItemsSource = refreshedItems;
        grid.UpdateLayout();
    }

    private static void ExerciseCollectionViews(IList<TestItem> items)
    {
        var view = new DataGridCollectionView(items);
        using (view.DeferRefresh())
        {
            view.Filter = item => ((TestItem)item).Value % 2 == 0;
            view.SortDescriptions.Add(DataGridSortDescription.FromPath(nameof(TestItem.Value), ListSortDirection.Descending));
            view.GroupDescriptions.Add(new DataGridPathGroupDescription(nameof(TestItem.Group)));
        }

        var pagedView = new DataGridCollectionView(items);
        using (pagedView.DeferRefresh())
        {
            pagedView.GroupDescriptions.Add(new DataGridPathGroupDescription(nameof(TestItem.Group)));
            pagedView.PageSize = 5;
        }
    }

    private sealed class TestItem
    {
        public TestItem(string name, string group, int value)
        {
            Name = name;
            Group = group;
            Value = value;
        }

        public string Name { get; }
        public string Group { get; }
        public int Value { get; }
    }

    private sealed class DiagnosticsListener : IDisposable
    {
        private readonly ActivityListener _activityListener;
        private readonly MeterListener _meterListener;
        private readonly List<Activity> _activities = new();
        private readonly Dictionary<string, List<double>> _doubleMeasurements = new(StringComparer.Ordinal);
        private readonly Dictionary<string, List<long>> _longMeasurements = new(StringComparer.Ordinal);
        private readonly Dictionary<string, List<Dictionary<string, object?>>> _longMeasurementTags = new(StringComparer.Ordinal);

        public DiagnosticsListener()
        {
            _activityListener = new ActivityListener
            {
                ShouldListenTo = source => source.Name == DataGridDiagnostics.ActivitySourceName,
                Sample = static (ref ActivityCreationOptions<ActivityContext> _) => ActivitySamplingResult.AllDataAndRecorded,
                ActivityStopped = activity => _activities.Add(activity),
            };

            ActivitySource.AddActivityListener(_activityListener);

            _meterListener = new MeterListener
            {
                InstrumentPublished = (instrument, listener) =>
                {
                    if (instrument.Meter.Name == DataGridDiagnostics.MeterName)
                    {
                        listener.EnableMeasurementEvents(instrument);
                    }
                }
            };

            _meterListener.SetMeasurementEventCallback<double>((instrument, measurement, tags, _) =>
            {
                if (!_doubleMeasurements.TryGetValue(instrument.Name, out var values))
                {
                    values = new List<double>();
                    _doubleMeasurements[instrument.Name] = values;
                }

                values.Add(measurement);
            });

            _meterListener.SetMeasurementEventCallback<long>((instrument, measurement, tags, _) =>
            {
                if (!_longMeasurements.TryGetValue(instrument.Name, out var values))
                {
                    values = new List<long>();
                    _longMeasurements[instrument.Name] = values;
                }

                values.Add(measurement);

                if (tags.Length > 0)
                {
                    if (!_longMeasurementTags.TryGetValue(instrument.Name, out var tagEntries))
                    {
                        tagEntries = new List<Dictionary<string, object?>>();
                        _longMeasurementTags[instrument.Name] = tagEntries;
                    }

                    var entry = new Dictionary<string, object?>(StringComparer.Ordinal);
                    foreach (var tag in tags)
                    {
                        entry[tag.Key] = tag.Value;
                    }

                    tagEntries.Add(entry);
                }
            });

            _meterListener.Start();
        }

        public IReadOnlyList<Activity> Activities => _activities;
        public IReadOnlyDictionary<string, List<double>> DoubleMeasurements => _doubleMeasurements;
        public IReadOnlyDictionary<string, List<long>> LongMeasurements => _longMeasurements;
        public IReadOnlyDictionary<string, List<Dictionary<string, object?>>> LongMeasurementTags => _longMeasurementTags;

        public void Dispose()
        {
            _meterListener.Dispose();
            _activityListener.Dispose();
        }
    }
}
