using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Windows.Input;
using System.Diagnostics.CodeAnalysis;
using Avalonia.Controls;
using Avalonia.Controls.Templates;
using Avalonia.Data;
using Avalonia.Layout;
using DataGridSample.Models;
using DataGridSample.Mvvm;

namespace DataGridSample.ViewModels
{
    public class BindableColumnsViewModel : ObservableObject
    {
        private ColumnsSynchronizationMode _columnsSyncMode = ColumnsSynchronizationMode.OneWayToGrid;
        private ColumnsSourceResetBehavior _resetBehavior = ColumnsSourceResetBehavior.Reload;
        private AutoGeneratedColumnsPlacement _autoPlacement = AutoGeneratedColumnsPlacement.AfterSource;

        public BindableColumnsViewModel()
        {
            Items = new ObservableCollection<Person>(CreatePeople());
            Columns = new ObservableCollection<DataGridColumn>();
            ColumnPreviews = new ObservableCollection<ColumnPreview>();

            SetPresetACommand = new RelayCommand(_ => ApplyPresetA());
            SetPresetBCommand = new RelayCommand(_ => ApplyPresetB());
            AddColumnCommand = new RelayCommand(_ => AddTrailingColumn());
            RemoveLastColumnCommand = new RelayCommand(_ => RemoveLastColumn(), _ => Columns.Any());
            MoveLastToFirstCommand = new RelayCommand(_ => MoveLastToFirst(), _ => Columns.Count > 1);

            ApplyPresetA();
        }

        public ObservableCollection<Person> Items { get; }

        public ObservableCollection<DataGridColumn> Columns { get; }

        public ObservableCollection<ColumnPreview> ColumnPreviews { get; }

        public ColumnsSynchronizationMode ColumnsSyncMode
        {
            get => _columnsSyncMode;
            set => SetProperty(ref _columnsSyncMode, value);
        }

        public ColumnsSourceResetBehavior ColumnsResetBehavior
        {
            get => _resetBehavior;
            set => SetProperty(ref _resetBehavior, value);
        }

        public AutoGeneratedColumnsPlacement AutoGeneratedPlacement
        {
            get => _autoPlacement;
            set => SetProperty(ref _autoPlacement, value);
        }

        public Array SyncModes => Enum.GetValues(typeof(ColumnsSynchronizationMode));

        public Array ResetBehaviors => Enum.GetValues(typeof(ColumnsSourceResetBehavior));

        public Array AutoPlacements => Enum.GetValues(typeof(AutoGeneratedColumnsPlacement));

        public ICommand SetPresetACommand { get; }

        public ICommand SetPresetBCommand { get; }

        public ICommand AddColumnCommand { get; }

        public ICommand RemoveLastColumnCommand { get; }

        public ICommand MoveLastToFirstCommand { get; }

        private void ApplyPresetA()
        {
            Columns.Clear();
            Columns.Add(CreateTextColumn("First Name", "FirstName", p => p.FirstName, 1.5));
            Columns.Add(CreateTextColumn("Last Name", "LastName", p => p.LastName, 1.5));
            // Leave Age to auto-generation to demo placement.
            RefreshColumnPreviews();
        }

        private void ApplyPresetB()
        {
            Columns.Clear();
            Columns.Add(CreateTextColumn("Name", "FirstName", p => p.FirstName, 1.5));
            Columns.Add(CreateCheckColumn("Banned", "IsBanned", p => p.IsBanned, 0.8));
            Columns.Add(CreateTextColumn("Age", "Age", p => p.Age, 0.8));
            RefreshColumnPreviews();
        }

        private void AddTrailingColumn()
        {
            var index = Columns.Count + 1;
            Columns.Add(CreateTextColumn($"Extra {index}", "FirstName", p => p.FirstName, 1));
            RaiseCommandCanExecute();
            RefreshColumnPreviews();
        }

        private void RemoveLastColumn()
        {
            if (Columns.Any())
            {
                Columns.RemoveAt(Columns.Count - 1);
                RaiseCommandCanExecute();
                RefreshColumnPreviews();
            }
        }

        private void MoveLastToFirst()
        {
            if (Columns.Count > 1)
            {
                var last = Columns[Columns.Count - 1];
                Columns.RemoveAt(Columns.Count - 1);
                Columns.Insert(0, last);
                RefreshColumnPreviews();
            }
        }

        private static DataGridTemplateColumn CreateTextColumn(string header, string path, Func<Person, object?> selector, double starWeight)
        {
            return new DataGridTemplateColumn
            {
                Header = header,
                Tag = path,
                Width = new DataGridLength(starWeight, DataGridLengthUnitType.Star),
                CellTemplate = new FuncDataTemplate<Person>((item, _) =>
                    new TextBlock
                    {
                        Text = selector(item)?.ToString() ?? string.Empty
                    })
            };
        }

        private static DataGridTemplateColumn CreateCheckColumn(string header, string path, Func<Person, bool> selector, double width)
        {
            return new DataGridTemplateColumn
            {
                Header = header,
                Tag = path,
                Width = new DataGridLength(width, DataGridLengthUnitType.Star),
                CellTemplate = new FuncDataTemplate<Person>((item, _) =>
                    new CheckBox
                    {
                        IsChecked = selector(item),
                        IsEnabled = false
                    })
            };
        }

        private static ObservableCollection<Person> CreatePeople()
        {
            return new ObservableCollection<Person>
            {
                new() { FirstName = "Ada", LastName = "Lovelace", Age = 36, IsBanned = false },
                new() { FirstName = "Alan", LastName = "Turing", Age = 41, IsBanned = false },
                new() { FirstName = "Grace", LastName = "Hopper", Age = 85, IsBanned = false },
                new() { FirstName = "Jean", LastName = "Bartik", Age = 86, IsBanned = false },
                new() { FirstName = "Claude", LastName = "Shannon", Age = 84, IsBanned = true },
            };
        }

        private void RaiseCommandCanExecute()
        {
            (RemoveLastColumnCommand as RelayCommand)?.RaiseCanExecuteChanged();
            (MoveLastToFirstCommand as RelayCommand)?.RaiseCanExecuteChanged();
        }

        private void RefreshColumnPreviews()
        {
            ColumnPreviews.Clear();
            foreach (var column in Columns)
            {
                var path = column.Tag as string ?? string.Empty;
                ColumnPreviews.Add(new ColumnPreview(column.Header?.ToString() ?? "(unnamed)", path, column.GetType().Name));
            }
        }

        [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicProperties)]
        public record ColumnPreview(string Header, string Path, string ColumnType);
    }
}
