// Copyright (c) Wieslaw Soltes. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ProDataGrid.SourceGenerators;

public sealed partial class ProDataGridGenerator
{
    internal const string GenerateColumnsAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridColumnsAttribute";
    internal const string GenerateColumnsForNamespaceAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridColumnsForNamespaceAttribute";
    internal const string GenerateViewModelAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewModelAttribute";
    internal const string GenerateControllerAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridControllerAttribute";
    internal const string GenerateViewModelsForNamespaceAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewModelsForNamespaceAttribute";
    internal const string ColumnAttributeName = "ProDataGrid.SourceGeneration.DataGridColumnAttribute";
    internal const string IgnoreColumnAttributeName = "ProDataGrid.SourceGeneration.DataGridIgnoreColumnAttribute";
    internal const string KeyAttributeName = "ProDataGrid.SourceGeneration.DataGridKeyAttribute";
    internal const string ChildrenAttributeName = "ProDataGrid.SourceGeneration.DataGridChildrenAttribute";
    internal const string ExpandedAttributeName = "ProDataGrid.SourceGeneration.DataGridExpandedAttribute";
    internal const string ParentKeyAttributeName = "ProDataGrid.SourceGeneration.DataGridParentKeyAttribute";
    internal const string GroupAttributeName = "ProDataGrid.SourceGeneration.DataGridGroupAttribute";
    internal const string SummaryAttributeName = "ProDataGrid.SourceGeneration.DataGridSummaryAttribute";
    internal const string ConditionalFormatAttributeName = "ProDataGrid.SourceGeneration.DataGridConditionalFormatAttribute";
    internal const string BandAttributeName = "ProDataGrid.SourceGeneration.DataGridBandAttribute";
    internal const string PivotAxisAttributeName = "ProDataGrid.SourceGeneration.DataGridPivotAxisAttribute";
    internal const string PivotValueAttributeName = "ProDataGrid.SourceGeneration.DataGridPivotValueAttribute";
    internal const string ChartFieldAttributeName = "ProDataGrid.SourceGeneration.DataGridChartFieldAttribute";
    internal const string OutlineFieldAttributeName = "ProDataGrid.SourceGeneration.DataGridOutlineFieldAttribute";
    internal const string FormulaFieldAttributeName = "ProDataGrid.SourceGeneration.DataGridFormulaFieldAttribute";
    internal const string GenerateViewAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewAttribute";
    internal const string GenerateViewsForNamespaceAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewsForNamespaceAttribute";
    internal const string GenerateRegistryAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridRegistryAttribute";
    internal const string ViewRegistrationAttributeName = "ProDataGrid.SourceGeneration.DataGridViewRegistrationAttribute";
    internal const string GenerateIndexedColumnsAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridIndexedColumnsAttribute";
    internal const string GenerateCellDrawCacheAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridCellDrawCacheAttribute";

    private static void RegisterAttributeSources(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
            postInitializationContext.AddSource(
                "ProDataGrid.SourceGeneration.Attributes.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));
    }

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        using System;

        namespace ProDataGrid.SourceGeneration
        {
            internal enum DataGridColumnKind
            {
                Auto,
                Text,
                CheckBox,
                Hyperlink,
                Image,
                Numeric,
                ProgressBar,
                Slider,
                DatePicker,
                TimePicker,
                MaskedText,
                AutoComplete,
                ToggleButton,
                ToggleSwitch,
                Hierarchical,
                CustomDrawing,
                ComboBoxSelectedItem,
                ComboBoxSelectedValue,
                ComboBoxText,
                Template,
                Button,
                Formula
            }

            internal enum DataGridColumnDiscovery
            {
                PublicProperties,
                AttributedOnly
            }

            internal enum DataGridViewFramework
            {
                Avalonia,
                ReactiveUI
            }

            internal enum DataGridViewRecipe
            {
                GridOnly,
                SearchableGrid,
                OperationsToolbar,
                Explorer,
                Spreadsheet,
                Analytics,
                MasterDetail
            }

            internal enum DataGridCondition
            {
                Equals,
                NotEquals,
                GreaterThan,
                GreaterThanOrEqual,
                LessThan,
                LessThanOrEqual,
                IsNull,
                IsNotNull,
                Custom,
                Between,
                Contains,
                StartsWith,
                EndsWith
            }

            internal enum DataGridFrozenPlacement
            {
                None,
                Left,
                Right
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = false)]
            internal sealed class GenerateDataGridRegistryAttribute : Attribute
            {
                public string RegistryName { get; set; } = "GeneratedProDataGridRegistration";
                public string RegistryNamespace { get; set; } = "ProDataGrid.Generated";
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class DataGridViewRegistrationAttribute : Attribute
            {
                public DataGridViewRegistrationAttribute(Type viewModelType, Type viewType)
                {
                    ViewModelType = viewModelType;
                    ViewType = viewType;
                }

                public Type ViewModelType { get; }
                public Type ViewType { get; }
            }

            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridIndexedColumnsAttribute : Attribute
            {
                public string Name { get; set; } = "IndexedColumns";
                public string? GetterMethod { get; set; }
                public string? SetterMethod { get; set; }
                public string? NotificationNameMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class GenerateDataGridCellDrawCacheAttribute : Attribute
            {
                public int InitialCapacity { get; set; }
                public int MaximumCapacity { get; set; } = 256;
                public bool GenerateSlotConstants { get; set; } = true;
            }

            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridColumnsAttribute : Attribute
            {
                public GenerateDataGridColumnsAttribute() { }
                public GenerateDataGridColumnsAttribute(Type itemType) { ItemType = itemType; }

                public Type? ItemType { get; }
                public string? ProviderName { get; set; }
                public string? ProviderNamespace { get; set; }
                public string? SchemaId { get; set; }
                public int StateVersion { get; set; } = 1;
                public DataGridColumnDiscovery Discovery { get; set; } = DataGridColumnDiscovery.PublicProperties;
                public bool IncludeInherited { get; set; } = true;
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
                public bool HierarchicalRows { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedPerformanceProfile PerformanceProfile { get; set; }
                public int DefaultPageSize { get; set; }
                public int InitialPageIndex { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedInitialCurrency InitialCurrency { get; set; }
                public bool PreserveCurrentItemByKey { get; set; } = true;
                public bool PreserveSelectionByKey { get; set; } = true;
                public Type? ImplementationType { get; set; }
                public Type? MutationHandlerType { get; set; }
                public Type? NewRowFactoryType { get; set; }
                public Type? FormulaFillTranslatorType { get; set; }
                public string[] OperationPresetMethods { get; set; } = Array.Empty<string>();
                public string? KeySelectorMethod { get; set; }
                public bool UseReferenceIdentityKey { get; set; }
                public string? ConfigureMethod { get; set; }
                public string? PivotConfigureMethod { get; set; }
                public string? OutlineConfigureMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateDataGridColumnsForNamespaceAttribute : Attribute
            {
                public GenerateDataGridColumnsForNamespaceAttribute(string namespaceName) { NamespaceName = namespaceName; }

                public string NamespaceName { get; }
                public bool IncludeNestedNamespaces { get; set; } = true;
                public DataGridColumnDiscovery Discovery { get; set; } = DataGridColumnDiscovery.PublicProperties;
                public bool IncludeInherited { get; set; } = true;
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
                public bool HierarchicalRows { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedPerformanceProfile PerformanceProfile { get; set; }
                public int DefaultPageSize { get; set; }
                public int InitialPageIndex { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedInitialCurrency InitialCurrency { get; set; }
                public bool PreserveCurrentItemByKey { get; set; } = true;
                public bool PreserveSelectionByKey { get; set; } = true;
                public int StateVersion { get; set; } = 1;
                public string? PivotConfigureMethod { get; set; }
                public string? OutlineConfigureMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridViewModelAttribute : Attribute
            {
                public GenerateDataGridViewModelAttribute(Type itemType) { ItemType = itemType; }
                public GenerateDataGridViewModelAttribute(Type viewModelType, Type itemType)
                {
                    ViewModelType = viewModelType;
                    ItemType = itemType;
                }

                public Type? ViewModelType { get; }
                public Type ItemType { get; }
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string SchemaPropertyName { get; set; } = "DataGridSchema";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public bool GenerateNavigationModel { get; set; }
                public string NavigationModelPropertyName { get; set; } = "NavigationModel";
                public bool GenerateNavigationInputModel { get; set; }
                public string NavigationInputModelPropertyName { get; set; } = "NavigationInputModel";
                public bool GenerateRouteContextFactory { get; set; }
                public string RouteContextFactoryPropertyName { get; set; } = "RouteContextFactory";
                public string? ProviderName { get; set; }
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
            }

            [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridControllerAttribute : Attribute
            {
                public GenerateDataGridControllerAttribute(Type itemType, string name)
                {
                    ItemType = itemType;
                    Name = name;
                }

                public Type ItemType { get; }
                public string Name { get; }
                public string? ProviderName { get; set; }
                public string? SourceMember { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedSourceKind SourceKind { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedFeatures Features { get; set; } =
                    global::Avalonia.Controls.DataGridGeneratedFeatures.Columns |
                    global::Avalonia.Controls.DataGridGeneratedFeatures.Operations;
                public global::Avalonia.Controls.DataGridOperationExecution OperationExecution { get; set; }
                public string? KeyMember { get; set; }
                public string? KeySelectorMethod { get; set; }
                public bool UseReferenceIdentityKey { get; set; }
                public Type? ImplementationType { get; set; }
                public string? ConfigureMethod { get; set; }
                public string? PipelineTransformMethod { get; set; }
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateDataGridViewModelsForNamespaceAttribute : Attribute
            {
                public GenerateDataGridViewModelsForNamespaceAttribute(string namespaceName) { NamespaceName = namespaceName; }

                public string NamespaceName { get; }
                public bool IncludeNestedNamespaces { get; set; } = true;
                public string ItemsPropertyName { get; set; } = "Items";
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string SchemaPropertyName { get; set; } = "DataGridSchema";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public bool GenerateNavigationModel { get; set; }
                public string NavigationModelPropertyName { get; set; } = "NavigationModel";
                public bool GenerateNavigationInputModel { get; set; }
                public string NavigationInputModelPropertyName { get; set; } = "NavigationInputModel";
                public bool GenerateRouteContextFactory { get; set; }
                public string RouteContextFactoryPropertyName { get; set; } = "RouteContextFactory";
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
            }

            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridViewAttribute : Attribute
            {
                public GenerateDataGridViewAttribute(Type itemType) { ItemType = itemType; }
                public GenerateDataGridViewAttribute(Type viewModelType, Type itemType)
                {
                    ViewModelType = viewModelType;
                    ItemType = itemType;
                }

                public Type? ViewModelType { get; }
                public Type ItemType { get; }
                public string? ViewName { get; set; }
                public string? ViewNamespace { get; set; }
                public DataGridViewFramework Framework { get; set; } = DataGridViewFramework.Avalonia;
                public Type? BaseType { get; set; }
                public string? Title { get; set; }
                public string ItemsPropertyName { get; set; } = "Items";
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public string? SortingModelPropertyName { get; set; }
                public string? FilteringModelPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridFiltering.DataGridHierarchyFilterPolicy HierarchyFilterPolicy { get; set; } =
                    global::Avalonia.Controls.DataGridFiltering.DataGridHierarchyFilterPolicy.KeepAncestorsOfMatches;
                public string? SearchModelPropertyName { get; set; }
                public string? SearchTextPropertyName { get; set; }
                public string? SelectionModelPropertyName { get; set; }
                public string? NavigationModelPropertyName { get; set; }
                public string? RouteNavigationModelPropertyName { get; set; }
                public string? NavigationInputModelPropertyName { get; set; }
                public string? RouteContextFactoryPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridSelectionMode SelectionMode { get; set; } =
                    global::Avalonia.Controls.DataGridSelectionMode.Single;
                public global::Avalonia.Controls.DataGridSelectionUnit SelectionUnit { get; set; } =
                    global::Avalonia.Controls.DataGridSelectionUnit.FullRow;
                public string? ClipboardImportModelPropertyName { get; set; }
                public string? FillModelPropertyName { get; set; }
                public string? FormulaModelPropertyName { get; set; }
                public string? ConditionalFormattingModelPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridEditTriggers EditTriggers { get; set; } =
                    global::Avalonia.Controls.DataGridEditTriggers.Default;
                public bool RestrictTextInputEditToCells { get; set; }
                public global::Avalonia.Input.KeyModifiers RequiredPointerEditModifiers { get; set; }
                public bool RequireExactPointerEditModifiers { get; set; }
                public global::Avalonia.Controls.DataGridClipboardCopyMode ClipboardCopyMode { get; set; } =
                    global::Avalonia.Controls.DataGridClipboardCopyMode.ExcludeHeader;
                public bool IsReadOnly { get; set; }
                public bool CanUserAddRows { get; set; }
                public bool CanUserDeleteRows { get; set; }
                public bool ShowTotalSummary { get; set; }
                public bool ShowGroupSummary { get; set; }
                public global::Avalonia.Controls.DataGridSummaryRowPosition TotalSummaryPosition { get; set; } =
                    global::Avalonia.Controls.DataGridSummaryRowPosition.Bottom;
                public global::Avalonia.Controls.DataGridGroupSummaryPosition GroupSummaryPosition { get; set; } =
                    global::Avalonia.Controls.DataGridGroupSummaryPosition.Footer;
                public string? HierarchicalModelPropertyName { get; set; }
                public string? StateControllerPropertyName { get; set; }
                public string? ViewStatePropertyName { get; set; }
                public string? ErrorMessagePropertyName { get; set; }
                public string? RetryCommandPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedViewEventKinds RoutedEvents { get; set; }
                public string? RoutedEventCommandPropertyName { get; set; }
                public string[]? InteractionPropertyNames { get; set; }
                public Type[]? InteractionHandlerTypes { get; set; }
                public string? NavigationInteractionPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedPerformanceProfile PerformanceProfile { get; set; }
                public Type? InputMapType { get; set; }
                public string? InputCommandPropertyName { get; set; }
                public Type? DiagnosticsSinkType { get; set; }
                public string? DiagnosticsStatusPropertyName { get; set; }
                public string? ViewThemeKey { get; set; }
                public string? DataGridThemeKey { get; set; }
                public string? ToolbarThemeKey { get; set; }
                public string? RecipeContentThemeKey { get; set; }
                public string[]? ViewClasses { get; set; }
                public string[]? DataGridClasses { get; set; }
                public string[]? ToolbarClasses { get; set; }
                public string[]? RecipeContentClasses { get; set; }
                public string LoadingText { get; set; } = "Loading data…";
                public string EmptyText { get; set; } = "No items to display.";
                public string ErrorText { get; set; } = "Unable to load data.";
                public string RetryText { get; set; } = "Retry";
                public string? RowDetailsTemplateKey { get; set; }
                public Type? RowDetailsTemplateImplementationType { get; set; }
                public string? RowDetailsTemplateFactoryMethod { get; set; }
                public global::Avalonia.Controls.DataGridRowDetailsVisibilityMode RowDetailsVisibilityMode { get; set; } =
                    global::Avalonia.Controls.DataGridRowDetailsVisibilityMode.Collapsed;
                public bool AreRowDetailsFrozen { get; set; }
                public Type? RowDetailsNestedItemType { get; set; }
                public string? RowDetailsNestedItemsMember { get; set; }
                public string? RowDetailsNestedProviderName { get; set; }
                public string? RowDetailsNestedProviderNamespace { get; set; }
                public string? RowDetailsSummaryMember { get; set; }
                public string? RowDetailsAutomationId { get; set; }
                public DataGridViewRecipe Recipe { get; set; } = DataGridViewRecipe.SearchableGrid;
                public string? ControllerName { get; set; }
                public string? AutomationId { get; set; }
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateDataGridViewsForNamespaceAttribute : Attribute
            {
                public GenerateDataGridViewsForNamespaceAttribute(string namespaceName) { NamespaceName = namespaceName; }

                public string NamespaceName { get; }
                public bool IncludeNestedNamespaces { get; set; } = true;
                public DataGridViewFramework Framework { get; set; } = DataGridViewFramework.Avalonia;
                public Type? BaseType { get; set; }
                public string ItemsPropertyName { get; set; } = "Items";
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public string? SortingModelPropertyName { get; set; }
                public string? FilteringModelPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridFiltering.DataGridHierarchyFilterPolicy HierarchyFilterPolicy { get; set; } =
                    global::Avalonia.Controls.DataGridFiltering.DataGridHierarchyFilterPolicy.KeepAncestorsOfMatches;
                public string? SearchModelPropertyName { get; set; }
                public string? SearchTextPropertyName { get; set; }
                public string? SelectionModelPropertyName { get; set; }
                public string? NavigationModelPropertyName { get; set; }
                public string? RouteNavigationModelPropertyName { get; set; }
                public string? NavigationInputModelPropertyName { get; set; }
                public string? RouteContextFactoryPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridSelectionMode SelectionMode { get; set; } =
                    global::Avalonia.Controls.DataGridSelectionMode.Single;
                public global::Avalonia.Controls.DataGridSelectionUnit SelectionUnit { get; set; } =
                    global::Avalonia.Controls.DataGridSelectionUnit.FullRow;
                public string? ClipboardImportModelPropertyName { get; set; }
                public string? FillModelPropertyName { get; set; }
                public string? FormulaModelPropertyName { get; set; }
                public string? ConditionalFormattingModelPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridEditTriggers EditTriggers { get; set; } =
                    global::Avalonia.Controls.DataGridEditTriggers.Default;
                public bool RestrictTextInputEditToCells { get; set; }
                public global::Avalonia.Input.KeyModifiers RequiredPointerEditModifiers { get; set; }
                public bool RequireExactPointerEditModifiers { get; set; }
                public global::Avalonia.Controls.DataGridClipboardCopyMode ClipboardCopyMode { get; set; } =
                    global::Avalonia.Controls.DataGridClipboardCopyMode.ExcludeHeader;
                public bool IsReadOnly { get; set; }
                public bool CanUserAddRows { get; set; }
                public bool CanUserDeleteRows { get; set; }
                public bool ShowTotalSummary { get; set; }
                public bool ShowGroupSummary { get; set; }
                public global::Avalonia.Controls.DataGridSummaryRowPosition TotalSummaryPosition { get; set; } =
                    global::Avalonia.Controls.DataGridSummaryRowPosition.Bottom;
                public global::Avalonia.Controls.DataGridGroupSummaryPosition GroupSummaryPosition { get; set; } =
                    global::Avalonia.Controls.DataGridGroupSummaryPosition.Footer;
                public string? HierarchicalModelPropertyName { get; set; }
                public string? StateControllerPropertyName { get; set; }
                public string? ViewStatePropertyName { get; set; }
                public string? ErrorMessagePropertyName { get; set; }
                public string? RetryCommandPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedViewEventKinds RoutedEvents { get; set; }
                public string? RoutedEventCommandPropertyName { get; set; }
                public string[]? InteractionPropertyNames { get; set; }
                public Type[]? InteractionHandlerTypes { get; set; }
                public string? NavigationInteractionPropertyName { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedPerformanceProfile PerformanceProfile { get; set; }
                public Type? InputMapType { get; set; }
                public string? InputCommandPropertyName { get; set; }
                public Type? DiagnosticsSinkType { get; set; }
                public string? DiagnosticsStatusPropertyName { get; set; }
                public string? ViewThemeKey { get; set; }
                public string? DataGridThemeKey { get; set; }
                public string? ToolbarThemeKey { get; set; }
                public string? RecipeContentThemeKey { get; set; }
                public string[]? ViewClasses { get; set; }
                public string[]? DataGridClasses { get; set; }
                public string[]? ToolbarClasses { get; set; }
                public string[]? RecipeContentClasses { get; set; }
                public string LoadingText { get; set; } = "Loading data…";
                public string EmptyText { get; set; } = "No items to display.";
                public string ErrorText { get; set; } = "Unable to load data.";
                public string RetryText { get; set; } = "Retry";
                public string? RowDetailsTemplateKey { get; set; }
                public Type? RowDetailsTemplateImplementationType { get; set; }
                public string? RowDetailsTemplateFactoryMethod { get; set; }
                public global::Avalonia.Controls.DataGridRowDetailsVisibilityMode RowDetailsVisibilityMode { get; set; } =
                    global::Avalonia.Controls.DataGridRowDetailsVisibilityMode.Collapsed;
                public bool AreRowDetailsFrozen { get; set; }
                public Type? RowDetailsNestedItemType { get; set; }
                public string? RowDetailsNestedItemsMember { get; set; }
                public string? RowDetailsNestedProviderName { get; set; }
                public string? RowDetailsNestedProviderNamespace { get; set; }
                public string? RowDetailsSummaryMember { get; set; }
                public string? RowDetailsAutomationId { get; set; }
                public DataGridViewRecipe Recipe { get; set; } = DataGridViewRecipe.SearchableGrid;
                public string? ControllerName { get; set; }
                public string? AutomationId { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridColumnAttribute : Attribute
            {
                public DataGridColumnAttribute() { }
                public DataGridColumnAttribute(DataGridColumnKind kind) { Kind = kind; }

                public DataGridColumnKind Kind { get; set; } = DataGridColumnKind.Auto;
                public string? Header { get; set; }
                public string? Description { get; set; }
                public string? HeaderProviderMethod { get; set; }
                public string? DescriptionProviderMethod { get; set; }
                public int Order { get; set; }
                public int DisplayIndex { get; set; } = -1;
                public DataGridFrozenPlacement FrozenPlacement { get; set; }
                public string? ColumnKey { get; set; }
                public string[]? PreviousColumnKeys { get; set; }
                public string? SortMemberPath { get; set; }
                public string? Width { get; set; }
                public double MinWidth { get; set; }
                public double MaxWidth { get; set; }
                public bool CanUserSort { get; set; }
                public bool CanUserHide { get; set; }
                public bool CanUserResize { get; set; }
                public bool CanUserReorder { get; set; }
                public bool IsReadOnly { get; set; }
                public bool IsVisible { get; set; }
                public bool ShowFilterButton { get; set; }
                public string? HeaderTemplateKey { get; set; }
                public string? HeaderThemeKey { get; set; }
                public string? CellThemeKey { get; set; }
                public string? SummaryCellThemeKey { get; set; }
                public string? FilterThemeKey { get; set; }
                public string? FilterFlyoutKey { get; set; }
                public string? WidthSharingGroup { get; set; }
                public global::Avalonia.Controls.DataGridColumnDisplayMode DisplayMode { get; set; }
                public string? FormatString { get; set; }
                public string? Watermark { get; set; }
                public bool UseDirectTextCell { get; set; }
                public bool UseDirectCell { get; set; }
                public bool UseDirectTextContent { get; set; }
                public bool UseOptimizedPresenter { get; set; }
                public bool TrackDirectTextValueChanges { get; set; } = true;
                public bool UseDirectValueAccessor { get; set; }
                public bool TrackDirectValueChanges { get; set; } = true;
                public string? TemplateKey { get; set; }
                public string? EditingTemplateKey { get; set; }
                public string? TemplateFactoryMethod { get; set; }
                public string? EditingTemplateFactoryMethod { get; set; }
                public string? NewRowTemplateFactoryMethod { get; set; }
                public bool ReuseCellContent { get; set; }
                public Type? DrawOperationFactoryType { get; set; }
                public string? DrawOperationFactoryMethod { get; set; }
                public global::Avalonia.Controls.DataGridCustomDrawingMode DrawingMode { get; set; }
                public global::Avalonia.Controls.DataGridCustomDrawingRenderBackend RenderBackend { get; set; }
                public global::Avalonia.Controls.DataGridCustomDrawingTextLayoutCacheMode TextLayoutCacheMode { get; set; }
                public int SharedTextLayoutCacheCapacity { get; set; }
                public bool DrawOperationLayoutFastPath { get; set; }
                public string? Formula { get; set; }
                public string? FormulaName { get; set; }
                public string? Mask { get; set; }
                public string? Content { get; set; }
                public string? CheckedContent { get; set; }
                public string? UncheckedContent { get; set; }
                public string? OnContent { get; set; }
                public string? OffContent { get; set; }
                public string? ContentMember { get; set; }
                public string? CheckedContentMember { get; set; }
                public string? UncheckedContentMember { get; set; }
                public string? OnContentMember { get; set; }
                public string? OffContentMember { get; set; }
                public string? CommandMember { get; set; }
                public string? CommandParameterMember { get; set; }
                public string? ItemsSourceMember { get; set; }
                public string? DisplayMemberPath { get; set; }
                public string? SelectedValuePath { get; set; }
                public double Minimum { get; set; }
                public double Maximum { get; set; }
                public double Increment { get; set; }
                public bool IsThreeState { get; set; }
                public bool IsEditable { get; set; }
                public bool IsSearchable { get; set; }
                public string? SearchMemberPath { get; set; }
                public string? ConfigureMethod { get; set; }
                public string? FactoryMethod { get; set; }
                public string? ParserMethod { get; set; }
                public string? FormatterMethod { get; set; }
                public string? ValidatorMethod { get; set; }
                public string? AsyncValidatorMethod { get; set; }
                public string? CoerceMethod { get; set; }
                public string? CanEditMethod { get; set; }
                public string? ExportFormat { get; set; }
                public string? ExportNullText { get; set; }
                public string? BackendFieldName { get; set; }
                public global::Avalonia.Controls.DataGridGeneratedFilterEditorKind FilterEditor { get; set; }
                public string? FilterEditorResourceKey { get; set; }
                public string? HeaderResourceKey { get; set; }
                public string? DescriptionResourceKey { get; set; }
                public string? AutomationId { get; set; }
                public string? AutomationName { get; set; }
                public string? AutomationHelpText { get; set; }
                public bool IsSensitive { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridIgnoreColumnAttribute : Attribute
            {
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridGroupAttribute : Attribute
            {
                public int Order { get; set; }
                public global::System.ComponentModel.ListSortDirection Direction { get; set; } =
                    global::System.ComponentModel.ListSortDirection.Ascending;
                public string? FormatterMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
            internal sealed class DataGridSummaryAttribute : Attribute
            {
                public DataGridSummaryAttribute(global::Avalonia.Controls.DataGridAggregateType aggregate) { Aggregate = aggregate; }
                public global::Avalonia.Controls.DataGridAggregateType Aggregate { get; }
                public global::Avalonia.Controls.DataGridSummaryScope Scope { get; set; } =
                    global::Avalonia.Controls.DataGridSummaryScope.Both;
                public string? Format { get; set; }
                public string? Title { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
            internal sealed class DataGridConditionalFormatAttribute : Attribute
            {
                public DataGridConditionalFormatAttribute(DataGridCondition condition) { Condition = condition; }
                public DataGridCondition Condition { get; }
                public string? RuleId { get; set; }
                public string? Operand { get; set; }
                public string? Operand2 { get; set; }
                public global::System.StringComparison StringComparison { get; set; } =
                    global::System.StringComparison.Ordinal;
                public string? CellThemeKey { get; set; }
                public int Priority { get; set; }
                public bool StopIfTrue { get; set; } = true;
                public string? PredicateMethod { get; set; }
                public global::Avalonia.Controls.DataGridConditionalFormatting.ConditionalFormattingTarget Target { get; set; } =
                    global::Avalonia.Controls.DataGridConditionalFormatting.ConditionalFormattingTarget.Cell;
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
            internal sealed class DataGridBandAttribute : Attribute
            {
                public DataGridBandAttribute(string path) { Path = path; }
                public string Path { get; }
                public int Order { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
            internal sealed class DataGridPivotAxisAttribute : Attribute
            {
                public DataGridPivotAxisAttribute(global::Avalonia.Controls.DataGridGeneratedAnalyticsRole role) { Role = role; }
                public global::Avalonia.Controls.DataGridGeneratedAnalyticsRole Role { get; }
                public int Order { get; set; }
                public string? Name { get; set; }
                public string? Format { get; set; }
                public string? ConfigureMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
            internal sealed class DataGridPivotValueAttribute : Attribute
            {
                public DataGridPivotValueAttribute(global::Avalonia.Controls.DataGridPivoting.PivotAggregateType aggregate) { Aggregate = aggregate; }
                public global::Avalonia.Controls.DataGridPivoting.PivotAggregateType Aggregate { get; }
                public int Order { get; set; }
                public string? Name { get; set; }
                public string? Format { get; set; }
                public global::Avalonia.Controls.DataGridPivoting.PivotValueDisplayMode DisplayMode { get; set; }
                public string? Formula { get; set; }
                public string[] Dependencies { get; set; } = Array.Empty<string>();
                public string? CustomAggregatorFactoryMethod { get; set; }
                public string? ConfigureMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
            internal sealed class DataGridChartFieldAttribute : Attribute
            {
                public DataGridChartFieldAttribute(global::Avalonia.Controls.DataGridGeneratedAnalyticsRole role) { Role = role; }
                public global::Avalonia.Controls.DataGridGeneratedAnalyticsRole Role { get; }
                public int Order { get; set; }
                public string? Series { get; set; }
                public string? Format { get; set; }
                public global::Avalonia.Controls.DataGridAggregateType Aggregate { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = true, Inherited = true)]
            internal sealed class DataGridOutlineFieldAttribute : Attribute
            {
                public DataGridOutlineFieldAttribute(global::Avalonia.Controls.DataGridGeneratedAnalyticsRole role) { Role = role; }
                public global::Avalonia.Controls.DataGridGeneratedAnalyticsRole Role { get; }
                public int Order { get; set; }
                public string? Name { get; set; }
                public string? Format { get; set; }
                public global::Avalonia.Controls.DataGridAggregateType Aggregate { get; set; }
                public string? CustomAggregatorFactoryMethod { get; set; }
                public string? ConfigureMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridFormulaFieldAttribute : Attribute
            {
                public DataGridFormulaFieldAttribute(string name) { Name = name; }
                public string Name { get; }
                public string[]? Dependencies { get; set; }
                public int Order { get; set; }
                public string? Format { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridKeyAttribute : Attribute
            {
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridChildrenAttribute : Attribute
            {
                public string? LoaderMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridExpandedAttribute : Attribute
            {
            }

            [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridParentKeyAttribute : Attribute
            {
            }
        }
        """;
}
