// Copyright (c) Wieslaw Soltes. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace ProDataGrid.SourceGenerators;

internal static partial class Discovery
{
    public static ImmutableArray<IndexedColumnsCandidate> CreateIndexedColumnsCandidates(
        GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol targetType)
        {
            return ImmutableArray<IndexedColumnsCandidate>.Empty;
        }

        var candidates = ImmutableArray.CreateBuilder<IndexedColumnsCandidate>(context.Attributes.Length);
        foreach (AttributeData attribute in context.Attributes)
        {
            candidates.Add(new IndexedColumnsCandidate
            {
                TargetType = targetType,
                Attribute = attribute,
                CacheKey = CreateDirectSchemaCacheKey(targetType, ImmutableArray.Create(attribute))
            });
        }
        return candidates.ToImmutable();
    }

    public static IndexedColumnsGenerationResult BuildIndexedColumns(
        IndexedColumnsCandidate candidate,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        INamedTypeSymbol targetType = candidate.TargetType;
        Dictionary<string, TypedConstant> arguments = GeneratorUtilities.GetNamedArguments(candidate.Attribute);
        string name = GeneratorUtilities.GetString(arguments, "Name") ?? "IndexedColumns";
        string? getterName = GeneratorUtilities.GetString(arguments, "GetterMethod");
        string? setterName = GeneratorUtilities.GetString(arguments, "SetterMethod");
        string? notificationName = GeneratorUtilities.GetString(arguments, "NotificationNameMethod");
        Location location = candidate.Attribute.ApplicationSyntaxReference?.GetSyntax(cancellationToken).GetLocation() ??
            targetType.Locations.FirstOrDefault() ?? Location.None;

        if (targetType.TypeParameters.Length != 0 || targetType.IsStatic || string.IsNullOrWhiteSpace(name))
        {
            diagnostics.Add(Diagnostic.Create(
                GeneratorDiagnostics.InvalidTarget,
                location,
                targetType.ToDisplayString(),
                "indexed column families require a non-generic instance row type and a non-empty Name"));
            return new IndexedColumnsGenerationResult(null, diagnostics.ToImmutable());
        }

        IMethodSymbol? getter = FindIndexedGetter(targetType, getterName);
        if (getter == null)
        {
            diagnostics.Add(Diagnostic.Create(
                GeneratorDiagnostics.InvalidCustomizationMethod,
                location,
                getterName ?? string.Empty,
                targetType.ToDisplayString()));
        }
        IMethodSymbol? setter = string.IsNullOrWhiteSpace(setterName) ? null : FindIndexedSetter(targetType, setterName!);
        if (!string.IsNullOrWhiteSpace(setterName) && setter == null)
        {
            diagnostics.Add(Diagnostic.Create(
                GeneratorDiagnostics.InvalidCustomizationMethod,
                location,
                setterName,
                targetType.ToDisplayString()));
        }
        IMethodSymbol? notification = string.IsNullOrWhiteSpace(notificationName)
            ? null
            : FindNotificationName(targetType, notificationName!);
        if (!string.IsNullOrWhiteSpace(notificationName) && notification == null)
        {
            diagnostics.Add(Diagnostic.Create(
                GeneratorDiagnostics.InvalidCustomizationMethod,
                location,
                notificationName,
                targetType.ToDisplayString()));
        }
        if (getter == null || (!string.IsNullOrWhiteSpace(setterName) && setter == null) ||
            (!string.IsNullOrWhiteSpace(notificationName) && notification == null))
        {
            return new IndexedColumnsGenerationResult(null, diagnostics.ToImmutable());
        }

        string targetName = targetType.ToDisplayString(GeneratorUtilities.FullyQualifiedNullableFormat);
        string className = GeneratorUtilities.SanitizeIdentifier(targetType.Name + name);
        string namespaceName = targetType.ContainingNamespace?.ToDisplayString() ?? string.Empty;
        var source = new StringBuilder(4096);
        source.AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable");
        if (!string.IsNullOrEmpty(namespaceName))
        {
            source.Append("namespace ").Append(namespaceName).AppendLine()
                .AppendLine("{");
        }
        source.Append("    public static class ").Append(className).AppendLine()
            .AppendLine("    {")
            .AppendLine("        public static global::Avalonia.Controls.DataGridColumnDefinition CreateColumn<TValue>(")
            .AppendLine("            int index,")
            .AppendLine("            in global::Avalonia.Controls.DataGridGeneratedIndexedColumnOptions<TValue> options)")
            .AppendLine("        {")
            .AppendLine("            if (index < 0) throw new global::System.ArgumentOutOfRangeException(nameof(index));")
            .AppendLine("            var effective = options;");
        if (notification != null)
        {
            source.Append("            if (global::System.String.IsNullOrWhiteSpace(effective.PropertyName)) effective.PropertyName = ")
                .Append(targetName).Append('.').Append(GeneratorUtilities.EscapeIdentifier(notification.Name)).AppendLine("(index);");
        }
        source.Append("            return global::Avalonia.Controls.DataGridGeneratedIndexedColumnFactory.Create<")
            .Append(targetName).AppendLine(", TValue>(")
            .AppendLine("                index,")
            .Append("                item => (TValue)item.").Append(GeneratorUtilities.EscapeIdentifier(getter.Name)).AppendLine("(index)!,")
            .Append("                ");
        if (setter == null)
        {
            source.AppendLine("null,");
        }
        else
        {
            source.Append("(item, value) => item.").Append(GeneratorUtilities.EscapeIdentifier(setter.Name)).AppendLine("(index, value),");
        }
        source.AppendLine("                in effective);")
            .AppendLine("        }")
            .AppendLine()
            .AppendLine("        public static global::Avalonia.Controls.DataGridColumnDefinitionList CreateColumns<TValue>(")
            .AppendLine("            int count,")
            .AppendLine("            global::System.Func<int, global::Avalonia.Controls.DataGridGeneratedIndexedColumnOptions<TValue>> optionsFactory)")
            .AppendLine("        {")
            .AppendLine("            if (count < 0) throw new global::System.ArgumentOutOfRangeException(nameof(count));")
            .AppendLine("            if (optionsFactory is null) throw new global::System.ArgumentNullException(nameof(optionsFactory));")
            .AppendLine("            var columns = new global::Avalonia.Controls.DataGridColumnDefinitionList();")
            .AppendLine("            for (int index = 0; index < count; index++)")
            .AppendLine("            {")
            .AppendLine("                var options = optionsFactory(index);")
            .AppendLine("                columns.Add(CreateColumn<TValue>(index, in options));")
            .AppendLine("            }")
            .AppendLine("            return columns;")
            .AppendLine("        }")
            .AppendLine("    }");
        if (!string.IsNullOrEmpty(namespaceName))
        {
            source.AppendLine("}");
        }

        string hintName = namespaceName.Replace('.', '_') + "_" + className.Replace("@", string.Empty) + ".IndexedColumns.g.cs";
        return new IndexedColumnsGenerationResult(new GeneratedSource(hintName, source.ToString()), diagnostics.ToImmutable());
    }

    private static IMethodSymbol? FindIndexedGetter(INamedTypeSymbol type, string? name) =>
        string.IsNullOrWhiteSpace(name) ? null : type.GetMembers(name!).OfType<IMethodSymbol>().FirstOrDefault(static method =>
            !method.IsStatic && method.TypeParameters.Length == 0 && method.Parameters.Length == 1 &&
            method.Parameters[0].Type.SpecialType == SpecialType.System_Int32 &&
            !method.ReturnsVoid && IsCallable(method));

    private static IMethodSymbol? FindIndexedSetter(INamedTypeSymbol type, string name) =>
        type.GetMembers(name).OfType<IMethodSymbol>().FirstOrDefault(static method =>
            !method.IsStatic && method.TypeParameters.Length == 0 && method.Parameters.Length == 2 &&
            method.Parameters[0].Type.SpecialType == SpecialType.System_Int32 &&
            method.Parameters[1].Type.SpecialType == SpecialType.System_Object &&
            method.ReturnsVoid && IsCallable(method));

    private static IMethodSymbol? FindNotificationName(INamedTypeSymbol type, string name) =>
        type.GetMembers(name).OfType<IMethodSymbol>().FirstOrDefault(static method =>
            method.IsStatic && method.TypeParameters.Length == 0 && method.Parameters.Length == 1 &&
            method.Parameters[0].Type.SpecialType == SpecialType.System_Int32 &&
            method.ReturnType.SpecialType == SpecialType.System_String && IsCallable(method));

    private static bool IsCallable(IMethodSymbol method) =>
        method.DeclaredAccessibility == Accessibility.Public || method.DeclaredAccessibility == Accessibility.Internal ||
        method.DeclaredAccessibility == Accessibility.ProtectedOrInternal;
}
