using System.Text.Json;
using System.Text.Json.Serialization;

namespace Avalonia.Diagnostics.Remote;

[JsonSourceGenerationOptions(
    JsonSerializerDefaults.Web,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(RemotePreviewCapabilitiesRequest))]
[JsonSerializable(typeof(RemotePreviewSnapshotRequest))]
[JsonSerializable(typeof(RemoteTreeSnapshotRequest))]
[JsonSerializable(typeof(RemoteSelectionSnapshotRequest))]
[JsonSerializable(typeof(RemotePropertiesSnapshotRequest))]
[JsonSerializable(typeof(RemoteElements3DSnapshotRequest))]
[JsonSerializable(typeof(RemoteOverlayOptionsSnapshotRequest))]
[JsonSerializable(typeof(RemoteCodeDocumentsRequest))]
[JsonSerializable(typeof(RemoteCodeResolveNodeRequest))]
[JsonSerializable(typeof(RemoteBindingsSnapshotRequest))]
[JsonSerializable(typeof(RemoteStylesSnapshotRequest))]
[JsonSerializable(typeof(RemoteResourcesSnapshotRequest))]
[JsonSerializable(typeof(RemoteAssetsSnapshotRequest))]
[JsonSerializable(typeof(RemoteEventsSnapshotRequest))]
[JsonSerializable(typeof(RemoteBreakpointsSnapshotRequest))]
[JsonSerializable(typeof(RemoteLogsSnapshotRequest))]
[JsonSerializable(typeof(RemoteMetricsSnapshotRequest))]
[JsonSerializable(typeof(RemoteProfilerSnapshotRequest))]
[JsonSerializable(typeof(RemoteInspectHoveredRequest))]
[JsonSerializable(typeof(RemoteSetSelectionRequest))]
[JsonSerializable(typeof(RemoteSetPreviewPausedRequest))]
[JsonSerializable(typeof(RemoteSetPreviewSettingsRequest))]
[JsonSerializable(typeof(RemotePreviewInputRequest))]
[JsonSerializable(typeof(RemoteSetPropertyRequest))]
[JsonSerializable(typeof(RemoteSetPseudoClassRequest))]
[JsonSerializable(typeof(RemoteSetElements3DRootRequest))]
[JsonSerializable(typeof(RemoteSetElements3DFiltersRequest))]
[JsonSerializable(typeof(RemoteSetOverlayOptionsRequest))]
[JsonSerializable(typeof(RemoteSetOverlayLiveHoverRequest))]
[JsonSerializable(typeof(RemoteCodeDocumentOpenRequest))]
[JsonSerializable(typeof(RemoteAddPropertyBreakpointRequest))]
[JsonSerializable(typeof(RemoteAddEventBreakpointRequest))]
[JsonSerializable(typeof(RemoteRemoveBreakpointRequest))]
[JsonSerializable(typeof(RemoteToggleBreakpointRequest))]
[JsonSerializable(typeof(RemoteSetBreakpointsEnabledRequest))]
[JsonSerializable(typeof(RemoteSetEventEnabledRequest))]
[JsonSerializable(typeof(RemoteSetLogLevelsRequest))]
[JsonSerializable(typeof(RemoteSetPausedRequest))]
[JsonSerializable(typeof(RemoteSetMetricsSettingsRequest))]
[JsonSerializable(typeof(RemoteSetProfilerSettingsRequest))]
[JsonSerializable(typeof(RemoteEmptyMutationRequest))]
[JsonSerializable(typeof(RemoteTreeSnapshot))]
[JsonSerializable(typeof(RemoteSelectionSnapshot))]
[JsonSerializable(typeof(RemotePreviewCapabilitiesSnapshot))]
[JsonSerializable(typeof(RemotePreviewSnapshot))]
[JsonSerializable(typeof(RemotePreviewRectSnapshot))]
[JsonSerializable(typeof(RemotePropertiesSnapshot))]
[JsonSerializable(typeof(RemoteElements3DSnapshot))]
[JsonSerializable(typeof(RemoteOverlayOptionsSnapshot))]
[JsonSerializable(typeof(RemoteCodeDocumentsSnapshot))]
[JsonSerializable(typeof(RemoteCodeResolveNodeSnapshot))]
[JsonSerializable(typeof(RemoteBindingsSnapshot))]
[JsonSerializable(typeof(RemoteStylesSnapshot))]
[JsonSerializable(typeof(RemoteResourcesSnapshot))]
[JsonSerializable(typeof(RemoteAssetsSnapshot))]
[JsonSerializable(typeof(RemoteEventsSnapshot))]
[JsonSerializable(typeof(RemoteBreakpointsSnapshot))]
[JsonSerializable(typeof(RemoteLogsSnapshot))]
[JsonSerializable(typeof(RemoteMetricsSnapshot))]
[JsonSerializable(typeof(RemoteProfilerSnapshot))]
[JsonSerializable(typeof(RemoteMutationResult))]
[JsonSerializable(typeof(RemotePreviewStreamPayload))]
[JsonSerializable(typeof(RemoteMetricStreamPayload))]
[JsonSerializable(typeof(RemoteProfilerStreamPayload))]
[JsonSerializable(typeof(RemoteLogStreamPayload))]
[JsonSerializable(typeof(RemoteEventStreamPayload))]
[JsonSerializable(typeof(RemoteStreamTag))]
public partial class RemoteJsonSerializerContext : JsonSerializerContext
{
}
