using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Avalonia.Controls;

internal static partial class DataGridDiagnostics
{
    private static Histogram<double>? s_dataGridRefresh;
    private static Histogram<double>? s_rowsRefresh;
    private static Histogram<double>? s_rowsDisplayUpdate;
    private static Histogram<double>? s_rowGenerate;
    private static Histogram<double>? s_columnsAutoGenerate;
    private static Histogram<double>? s_selectionChanged;
    private static Histogram<double>? s_collectionRefresh;
    private static Histogram<double>? s_collectionFilter;
    private static Histogram<double>? s_collectionSort;
    private static Histogram<double>? s_collectionGroup;
    private static Histogram<double>? s_collectionGroupTemporary;
    private static Histogram<double>? s_collectionGroupPage;

    private static Counter<long>? s_rowsRealized;
    private static Counter<long>? s_rowsRecycled;
    private static Counter<long>? s_rowsPrepared;
    private static Counter<long>? s_rowsDisplayReused;
    private static Counter<long>? s_columnsAutoGenerated;
    private static Counter<long>? s_selectionChangedCount;

    public static void InitMetrics()
    {
        var meter = new Meter(MeterName);

        s_dataGridRefresh = meter.CreateHistogram<double>(
            Meters.DataGridRefreshTimeName,
            Meters.MillisecondsUnit,
            Meters.DataGridRefreshTimeDescription);
        s_rowsRefresh = meter.CreateHistogram<double>(
            Meters.RowsRefreshTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsRefreshTimeDescription);
        s_rowsDisplayUpdate = meter.CreateHistogram<double>(
            Meters.RowsDisplayUpdateTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsDisplayUpdateTimeDescription);
        s_rowGenerate = meter.CreateHistogram<double>(
            Meters.RowGenerateTimeName,
            Meters.MillisecondsUnit,
            Meters.RowGenerateTimeDescription);
        s_columnsAutoGenerate = meter.CreateHistogram<double>(
            Meters.ColumnsAutoGenerateTimeName,
            Meters.MillisecondsUnit,
            Meters.ColumnsAutoGenerateTimeDescription);
        s_selectionChanged = meter.CreateHistogram<double>(
            Meters.SelectionChangedTimeName,
            Meters.MillisecondsUnit,
            Meters.SelectionChangedTimeDescription);
        s_collectionRefresh = meter.CreateHistogram<double>(
            Meters.CollectionRefreshTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionRefreshTimeDescription);
        s_collectionFilter = meter.CreateHistogram<double>(
            Meters.CollectionFilterTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionFilterTimeDescription);
        s_collectionSort = meter.CreateHistogram<double>(
            Meters.CollectionSortTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionSortTimeDescription);
        s_collectionGroup = meter.CreateHistogram<double>(
            Meters.CollectionGroupTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionGroupTimeDescription);
        s_collectionGroupTemporary = meter.CreateHistogram<double>(
            Meters.CollectionGroupTemporaryTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionGroupTemporaryTimeDescription);
        s_collectionGroupPage = meter.CreateHistogram<double>(
            Meters.CollectionGroupPageTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionGroupPageTimeDescription);

        s_rowsRealized = meter.CreateCounter<long>(
            Meters.RowsRealizedCountName,
            Meters.RowsUnit,
            Meters.RowsRealizedCountDescription);
        s_rowsRecycled = meter.CreateCounter<long>(
            Meters.RowsRecycledCountName,
            Meters.RowsUnit,
            Meters.RowsRecycledCountDescription);
        s_rowsPrepared = meter.CreateCounter<long>(
            Meters.RowsPreparedCountName,
            Meters.RowsUnit,
            Meters.RowsPreparedCountDescription);
        s_rowsDisplayReused = meter.CreateCounter<long>(
            Meters.RowsDisplayReusedCountName,
            Meters.RowsUnit,
            Meters.RowsDisplayReusedCountDescription);
        s_columnsAutoGenerated = meter.CreateCounter<long>(
            Meters.ColumnsAutoGeneratedCountName,
            Meters.ColumnsUnit,
            Meters.ColumnsAutoGeneratedCountDescription);
        s_selectionChangedCount = meter.CreateCounter<long>(
            Meters.SelectionChangedCountName,
            Meters.SelectionUnit,
            Meters.SelectionChangedCountDescription);
    }

    public static HistogramReportDisposable BeginDataGridRefresh() => Begin(s_dataGridRefresh);
    public static HistogramReportDisposable BeginRowsRefresh() => Begin(s_rowsRefresh);
    public static HistogramReportDisposable BeginRowsDisplayUpdate() => Begin(s_rowsDisplayUpdate);
    public static HistogramReportDisposable BeginRowGenerate() => Begin(s_rowGenerate);
    public static HistogramReportDisposable BeginColumnsAutoGenerate() => Begin(s_columnsAutoGenerate);
    public static HistogramReportDisposable BeginSelectionChanged() => Begin(s_selectionChanged);
    public static HistogramReportDisposable BeginCollectionRefresh() => Begin(s_collectionRefresh);
    public static HistogramReportDisposable BeginCollectionFilter() => Begin(s_collectionFilter);
    public static HistogramReportDisposable BeginCollectionSort() => Begin(s_collectionSort);
    public static HistogramReportDisposable BeginCollectionGroup() => Begin(s_collectionGroup);
    public static HistogramReportDisposable BeginCollectionGroupTemporary() => Begin(s_collectionGroupTemporary);
    public static HistogramReportDisposable BeginCollectionGroupPage() => Begin(s_collectionGroupPage);

    public static void RecordRowRealized(string source)
    {
        var counter = s_rowsRealized;
        if (counter is null)
        {
            return;
        }

        TagList tags = default;
        tags.Add(Tags.Source, source);
        counter.Add(1, tags);
    }

    public static void RecordRowRecycled() => s_rowsRecycled?.Add(1);

    public static void RecordRowPrepared() => s_rowsPrepared?.Add(1);

    public static void RecordRowsDisplayReused() => s_rowsDisplayReused?.Add(1);

    public static void RecordColumnsAutoGenerated(int count)
    {
        if (count <= 0)
        {
            return;
        }

        s_columnsAutoGenerated?.Add(count);
    }

    public static void RecordSelectionChanged(DataGridSelectionChangeSource source)
    {
        var counter = s_selectionChangedCount;
        if (counter is null)
        {
            return;
        }

        TagList tags = default;
        tags.Add(Tags.SelectionSource, source.ToString());
        counter.Add(1, tags);
    }

    private static HistogramReportDisposable Begin(Histogram<double>? histogram)
        => histogram is not null ? new HistogramReportDisposable(histogram) : default;

    internal readonly ref struct HistogramReportDisposable
    {
        private readonly Histogram<double>? _histogram;
        private readonly long _timestamp;

        public HistogramReportDisposable(Histogram<double> histogram)
        {
            _histogram = histogram;
            _timestamp = Stopwatch.GetTimestamp();
        }

        public void Dispose()
        {
            if (_histogram is null || _timestamp == 0)
            {
                return;
            }

            var elapsedMs = (Stopwatch.GetTimestamp() - _timestamp) * 1000.0 / Stopwatch.Frequency;
            _histogram.Record(elapsedMs);
        }
    }
}
