// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using System.Collections.Specialized;
using Avalonia.Collections;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Templates;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="ToggleButton" /> controls 
    /// for editing boolean values with a compact toggle button (alternative to ToggleSwitch).
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridToggleButtonColumn : DataGridBoundColumn
    {
        private ToggleButton _currentToggleButton;
        private DataGrid _owningGrid;
        private readonly Lazy<ControlTheme> _cellToggleButtonTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="ToggleButton" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellToggleButtonTheme => GetThemeValue(_cellToggleButtonTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridToggleButtonColumn"/> class.
        /// </summary>
        public DataGridToggleButtonColumn()
        {
            BindingTarget = ToggleButton.IsCheckedProperty;
            _cellToggleButtonTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellToggleButtonTheme"));
        }

        /// <summary>
        /// Defines the <see cref="Content"/> property.
        /// </summary>
        public static readonly StyledProperty<object> ContentProperty =
            ContentControl.ContentProperty.AddOwner<DataGridToggleButtonColumn>();

        /// <summary>
        /// Gets or sets the content displayed on the toggle button.
        /// </summary>
        public object Content
        {
            get => GetValue(ContentProperty);
            set => SetValue(ContentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="CheckedContent"/> property.
        /// </summary>
        public static readonly StyledProperty<object> CheckedContentProperty =
            AvaloniaProperty.Register<DataGridToggleButtonColumn, object>(nameof(CheckedContent));

        /// <summary>
        /// Gets or sets the content displayed when checked (if different from normal content).
        /// </summary>
        public object CheckedContent
        {
            get => GetValue(CheckedContentProperty);
            set => SetValue(CheckedContentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="UncheckedContent"/> property.
        /// </summary>
        public static readonly StyledProperty<object> UncheckedContentProperty =
            AvaloniaProperty.Register<DataGridToggleButtonColumn, object>(nameof(UncheckedContent));

        /// <summary>
        /// Gets or sets the content displayed when unchecked (if different from normal content).
        /// </summary>
        public object UncheckedContent
        {
            get => GetValue(UncheckedContentProperty);
            set => SetValue(UncheckedContentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="IsThreeState"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> IsThreeStateProperty =
            ToggleButton.IsThreeStateProperty.AddOwner<DataGridToggleButtonColumn>();

        /// <summary>
        /// Gets or sets whether three states are supported (nullable bool).
        /// </summary>
        public bool IsThreeState
        {
            get => GetValue(IsThreeStateProperty);
            set => SetValue(IsThreeStateProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ClickMode"/> property.
        /// </summary>
        public static readonly StyledProperty<ClickMode> ClickModeProperty =
            Button.ClickModeProperty.AddOwner<DataGridToggleButtonColumn>();

        /// <summary>
        /// Gets or sets how the button responds to clicks.
        /// </summary>
        public ClickMode ClickMode
        {
            get => GetValue(ClickModeProperty);
            set => SetValue(ClickModeProperty, value);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == ContentProperty
                || change.Property == CheckedContentProperty
                || change.Property == UncheckedContentProperty
                || change.Property == IsThreeStateProperty
                || change.Property == ClickModeProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is ToggleButton toggleButton)
            {
                toggleButton.IsChecked = (bool?)uneditedValue;
            }
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            var toggleButton = new ToggleButton
            {
                Margin = new Thickness(0)
            };

            if (CellToggleButtonTheme is { } theme)
            {
                toggleButton.Theme = theme;
            }

            ConfigureToggleButton(toggleButton, true);
            return toggleButton;
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            bool isEnabled = false;
            var toggleButton = new ToggleButton();

            if (CellToggleButtonTheme is { } theme)
            {
                toggleButton.Theme = theme;
            }

            if (EnsureOwningGrid())
            {
                if (cell.RowIndex != -1 && cell.ColumnIndex != -1 &&
                    cell.OwningRow != null &&
                    cell.OwningRow.Slot == this.OwningGrid.CurrentSlot &&
                    cell.ColumnIndex == this.OwningGrid.CurrentColumnIndex)
                {
                    isEnabled = true;
                    if (_currentToggleButton != null)
                    {
                        _currentToggleButton.IsEnabled = false;
                    }
                    _currentToggleButton = toggleButton;
                }
            }

            toggleButton.IsEnabled = isEnabled;
            toggleButton.IsHitTestVisible = false;
            ConfigureToggleButton(toggleButton, isEnabled);

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                toggleButton.Bind(BindingTarget, Binding);
            }

            return toggleButton;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is ToggleButton toggleButton)
            {
                void EditValue()
                {
                    if (toggleButton.IsThreeState)
                    {
                        switch (toggleButton.IsChecked)
                        {
                            case false:
                                toggleButton.IsChecked = true;
                                break;
                            case true:
                                toggleButton.IsChecked = null;
                                break;
                            case null:
                                toggleButton.IsChecked = false;
                                break;
                        }
                    }
                    else
                    {
                        toggleButton.IsChecked = !toggleButton.IsChecked;
                    }
                }

                bool? uneditedValue = toggleButton.IsChecked;

                if (editingEventArgs is PointerPressedEventArgs args)
                {
                    void ProcessPointerArgs()
                    {
                        Point position = args.GetPosition(toggleButton);
                        Rect rect = new Rect(0, 0, toggleButton.Bounds.Width, toggleButton.Bounds.Height);
                        if (rect.Contains(position))
                        {
                            EditValue();
                        }
                    }

                    void OnLayoutUpdated(object sender, EventArgs e)
                    {
                        if (toggleButton.Bounds.Width != 0 || toggleButton.Bounds.Height != 0)
                        {
                            toggleButton.LayoutUpdated -= OnLayoutUpdated;
                            ProcessPointerArgs();
                        }
                    }

                    if (toggleButton.Bounds.Width == 0 && toggleButton.Bounds.Height == 0)
                    {
                        toggleButton.LayoutUpdated += OnLayoutUpdated;
                    }
                    else
                    {
                        ProcessPointerArgs();
                    }
                }

                return uneditedValue;
            }

            return false;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is ToggleButton toggleButton)
            {
                ConfigureToggleButton(toggleButton, toggleButton.IsEnabled);
            }
            else
            {
                throw DataGridError.DataGrid.ValueIsNotAnInstanceOf("element", typeof(ToggleButton));
            }
        }

        private void Columns_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.Action == NotifyCollectionChangedAction.Remove && e.OldItems.Contains(this) && _owningGrid != null)
            {
                _owningGrid.ColumnsInternal.CollectionChanged -= Columns_CollectionChanged;
                _owningGrid.CurrentCellChanged -= OwningGrid_CurrentCellChanged;
                _owningGrid.KeyDown -= OwningGrid_KeyDown;
                _owningGrid.LoadingRow -= OwningGrid_LoadingRow;
                _owningGrid = null;
            }
        }

        private void ConfigureToggleButton(ToggleButton toggleButton, bool isEnabled)
        {
            toggleButton.HorizontalAlignment = HorizontalAlignment.Center;
            toggleButton.VerticalAlignment = VerticalAlignment.Center;
            toggleButton.IsThreeState = IsThreeState;
            toggleButton.ClickMode = ClickMode;

            // Set content based on checked state
            toggleButton.PropertyChanged -= ToggleButton_PropertyChanged;
            if (isEnabled && CheckedContent != null && UncheckedContent != null)
            {
                // Use checked/unchecked content if available
                UpdateToggleButtonContent(toggleButton);
                toggleButton.PropertyChanged += ToggleButton_PropertyChanged;
            }
            else if (Content != null)
            {
                toggleButton.Content = Content;
            }
        }

        private void ToggleButton_PropertyChanged(object sender, AvaloniaPropertyChangedEventArgs e)
        {
            if (e.Property == ToggleButton.IsCheckedProperty && sender is ToggleButton toggleButton)
            {
                UpdateToggleButtonContent(toggleButton);
            }
        }

        private void UpdateToggleButtonContent(ToggleButton toggleButton)
        {
            toggleButton.Content = toggleButton.IsChecked == true ? CheckedContent : UncheckedContent;
        }

        private bool EnsureOwningGrid()
        {
            if (OwningGrid != null)
            {
                if (OwningGrid != _owningGrid)
                {
                    _owningGrid = OwningGrid;
                    _owningGrid.ColumnsInternal.CollectionChanged += Columns_CollectionChanged;
                    _owningGrid.CurrentCellChanged += OwningGrid_CurrentCellChanged;
                    _owningGrid.KeyDown += OwningGrid_KeyDown;
                    _owningGrid.LoadingRow += OwningGrid_LoadingRow;
                }
                return true;
            }
            return false;
        }

        private void OwningGrid_CurrentCellChanged(object sender, DataGridCurrentCellChangedEventArgs e)
        {
            if (_currentToggleButton != null)
            {
                _currentToggleButton.IsEnabled = false;
            }

            if (OwningGrid != null && OwningGrid.CurrentColumn == this 
                && OwningGrid.IsSlotVisible(OwningGrid.CurrentSlot))
            {
                if (OwningGrid.DisplayData.GetDisplayedElement(OwningGrid.CurrentSlot) is DataGridRow row)
                {
                    ToggleButton toggleButton = GetCellContent(row) as ToggleButton;
                    if (toggleButton != null)
                    {
                        toggleButton.IsEnabled = true;
                    }
                    _currentToggleButton = toggleButton;
                }
            }
        }

        private void OwningGrid_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Space && OwningGrid.CurrentColumn == this)
            {
                if (_currentToggleButton != null && _currentToggleButton.IsEnabled)
                {
                    if (_currentToggleButton.IsThreeState)
                    {
                        switch (_currentToggleButton.IsChecked)
                        {
                            case false:
                                _currentToggleButton.IsChecked = true;
                                break;
                            case true:
                                _currentToggleButton.IsChecked = null;
                                break;
                            case null:
                                _currentToggleButton.IsChecked = false;
                                break;
                        }
                    }
                    else
                    {
                        _currentToggleButton.IsChecked = !_currentToggleButton.IsChecked;
                    }
                    e.Handled = true;
                }
            }
        }

        private void OwningGrid_LoadingRow(object sender, DataGridRowEventArgs e)
        {
            if (e.Row.Slot == OwningGrid.CurrentSlot)
            {
                var cell = e.Row.Cells[Index];
                if (cell.Content is ToggleButton toggleButton)
                {
                    toggleButton.IsEnabled = true;
                    _currentToggleButton = toggleButton;
                }
            }
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
