// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using System.Collections;
using System.Collections.Generic;
using Avalonia.Collections;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Templates;
using Avalonia.Controls.Utils;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Markup.Xaml.MarkupExtensions;
using Avalonia.Media;
using Avalonia.Reactive;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="ComboBox" /> controls in its cells.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridComboBoxColumn : DataGridColumn
    {
        private BindingBase _selectedItemBinding;
        private BindingBase _selectedValueBinding;
        private BindingBase _textBinding;
        private readonly Lazy<ControlTheme> _cellComboBoxTheme;
        private readonly Lazy<ControlTheme> _cellComboBoxDisplayTheme;
        /// <summary>
        /// Gets the theme applied to editing <see cref="ComboBox" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellComboBoxTheme => GetThemeValue(_cellComboBoxTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="ComboBox" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellComboBoxDisplayTheme => GetThemeValue(_cellComboBoxDisplayTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridComboBoxColumn"/> class.
        /// </summary>
        public DataGridComboBoxColumn()
        {
            _cellComboBoxTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellComboBoxTheme"));
            _cellComboBoxDisplayTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellComboBoxDisplayTheme"));
        }

        /// <summary>
        /// The ComboBox will attach to this ItemsSource.
        /// </summary>
        public static readonly StyledProperty<IEnumerable> ItemsSourceProperty =
            ItemsControl.ItemsSourceProperty.AddOwner<DataGridComboBoxColumn>();

        /// <summary>
        /// Gets or sets the collection used to generate the items for the combo box.
        /// </summary>
        public IEnumerable ItemsSource
        {
            get => GetValue(ItemsSourceProperty);
            set => SetValue(ItemsSourceProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ItemTemplate"/> property.
        /// </summary>
        public static readonly StyledProperty<IDataTemplate> ItemTemplateProperty =
            ItemsControl.ItemTemplateProperty.AddOwner<DataGridComboBoxColumn>();

        /// <summary>
        /// Defines the <see cref="ComboBox.IsEditable"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> IsEditableProperty =
            ComboBox.IsEditableProperty.AddOwner<DataGridComboBoxColumn>();

        /// <summary>
        /// Gets or sets the template used to display each item in the combo box.
        /// </summary>
        public IDataTemplate ItemTemplate
        {
            get => GetValue(ItemTemplateProperty);
            set => SetValue(ItemTemplateProperty, value);
        }

        /// <summary>
        /// Gets or sets whether the generated combo box allows free-form text entry.
        /// </summary>
        public bool IsEditable
        {
            get => GetValue(IsEditableProperty);
            set => SetValue(IsEditableProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="HorizontalContentAlignment"/> property.
        /// </summary>
        public static readonly StyledProperty<HorizontalAlignment> HorizontalContentAlignmentProperty =
            ContentControl.HorizontalContentAlignmentProperty.AddOwner<DataGridComboBoxColumn>();

        /// <summary>
        /// Gets or sets the horizontal alignment of the content.
        /// </summary>
        public HorizontalAlignment HorizontalContentAlignment
        {
            get => GetValue(HorizontalContentAlignmentProperty);
            set => SetValue(HorizontalContentAlignmentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="VerticalContentAlignment"/> property.
        /// </summary>
        public static readonly StyledProperty<VerticalAlignment> VerticalContentAlignmentProperty =
            ContentControl.VerticalContentAlignmentProperty.AddOwner<DataGridComboBoxColumn>();

        /// <summary>
        /// Gets or sets the vertical alignment of the content.
        /// </summary>
        public VerticalAlignment VerticalContentAlignment
        {
            get => GetValue(VerticalContentAlignmentProperty);
            set => SetValue(VerticalContentAlignmentProperty, value);
        }

        /// <summary>
        /// DisplayMemberPath is a simple way to define a default template
        /// that describes how to convert Items into UI elements by using the specified path.
        /// </summary>
        public static readonly StyledProperty<string> DisplayMemberPathProperty =
            AvaloniaProperty.Register<DataGridComboBoxColumn, string>(nameof(DisplayMemberPath), string.Empty);

        /// <summary>
        /// Gets or sets the path used to display the combo box items.
        /// </summary>
        public string DisplayMemberPath
        {
            get => GetValue(DisplayMemberPathProperty);
            set => SetValue(DisplayMemberPathProperty, value);
        }

        /// <summary>
        /// The path used to retrieve the SelectedValue from the SelectedItem.
        /// </summary>
        public static readonly StyledProperty<string> SelectedValuePathProperty =
            AvaloniaProperty.Register<DataGridComboBoxColumn, string>(nameof(SelectedValuePath), string.Empty);

        /// <summary>
        /// Gets or sets the path on the data item that is used to compute
        /// <see cref="Avalonia.Controls.Primitives.SelectingItemsControl.SelectedValue"/>.
        /// </summary>
        public string SelectedValuePath
        {
            get => GetValue(SelectedValuePathProperty);
            set => SetValue(SelectedValuePathProperty, value);
        }

        /// <summary>
        /// The binding applied to <see cref="Avalonia.Controls.Primitives.SelectingItemsControl.SelectedItem"/>.
        /// </summary>
        [AssignBinding]
        public BindingBase SelectedItemBinding
        {
            get => _selectedItemBinding;
            set
            {
                if (_selectedItemBinding != value)
                {
                    _selectedItemBinding = PrepareBinding(value, applyValueConverter: false);
                    UpdateSortMemberPath(_selectedItemBinding);
                    NotifyPropertyChanged(nameof(SelectedItemBinding));
                }
            }
        }

        /// <summary>
        /// The binding applied to <see cref="Avalonia.Controls.Primitives.SelectingItemsControl.SelectedValue"/>.
        /// </summary>
        [AssignBinding]
        public BindingBase SelectedValueBinding
        {
            get => _selectedValueBinding;
            set
            {
                if (_selectedValueBinding != value)
                {
                    _selectedValueBinding = PrepareBinding(value, applyValueConverter: false);
                    UpdateSortMemberPath(_selectedValueBinding);
                    NotifyPropertyChanged(nameof(SelectedValueBinding));
                }
            }
        }

        /// <summary>
        /// The binding applied to <see cref="ComboBox.Text"/>.
        /// </summary>
        [AssignBinding]
        public BindingBase TextBinding
        {
            get => _textBinding;
            set
            {
                if (_textBinding != value)
                {
                    _textBinding = PrepareBinding(value, applyValueConverter: true);
                    UpdateSortMemberPath(_textBinding);
                    NotifyPropertyChanged(nameof(TextBinding));
                }
            }
        }

        /// <summary>
        /// The binding that will be used to get or set cell content for the clipboard.
        /// </summary>
        public override BindingBase ClipboardContentBinding
        {
            get => base.ClipboardContentBinding ?? EffectiveBinding;
            set => base.ClipboardContentBinding = value;
        }

        /// <summary>
        /// Gets the binding that should be used for edit/clipboard operations.
        /// </summary>
        internal BindingBase EffectiveBinding
        {
            get
            {
                if (SelectedItemBinding != null)
                {
                    return SelectedItemBinding;
                }
                else if (SelectedValueBinding != null)
                {
                    return SelectedValueBinding;
                }

                return TextBinding;
            }
        }

        private AvaloniaProperty GetEffectiveTargetProperty()
        {
            if (SelectedItemBinding != null)
            {
                return SelectingItemsControl.SelectedItemProperty;
            }

            if (SelectedValueBinding != null)
            {
                return SelectingItemsControl.SelectedValueProperty;
            }

            return ComboBox.TextProperty;
        }

        /// <inheritdoc />
        public override bool IsReadOnly
        {
            get
            {
                if (IsOneWayBinding(EffectiveBinding))
                {
                    return true;
                }

                return base.IsReadOnly;
            }
            set => base.IsReadOnly = value;
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        /// <param name="editingElement">The element that the column displays for a cell in editing mode.</param>
        /// <param name="uneditedValue">The previous, unedited value in the cell being edited.</param>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is ComboBox comboBox)
            {
                var property = GetEffectiveTargetProperty();
                if (property == ComboBox.TextProperty)
                {
                    comboBox.Text = uneditedValue as string;
                }
                else if (property == SelectingItemsControl.SelectedItemProperty)
                {
                    comboBox.SelectedItem = uneditedValue;
                }
                else if (property == SelectingItemsControl.SelectedValueProperty)
                {
                    comboBox.SelectedValue = uneditedValue;
                }
            }
        }

        /// <summary>
        /// Gets a <see cref="ComboBox" /> control that is bound to the column's bindings.
        /// </summary>
        /// <param name="cell">The cell that will contain the generated element.</param>
        /// <param name="dataItem">The data item represented by the row that contains the intended cell.</param>
        /// <returns>A new <see cref="ComboBox" /> control that is bound to the column.</returns>
        protected override Control GenerateEditingElement(DataGridCell cell, object dataItem, out ICellEditBinding editBinding)
        {
            var comboBox = CreateComboBox(isEditing: true);

            ApplyColumnProperties(comboBox);

            editBinding = null;
            if (dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                var effectiveBinding = EffectiveBinding;
                if (effectiveBinding != null)
                {
                    editBinding = BindEditingElement(comboBox, GetEffectiveTargetProperty(), effectiveBinding);
                }

                ApplyBindings(comboBox, skipProperty: GetEffectiveTargetProperty());
            }

            return comboBox;
        }

        /// <summary>
        /// Gets a read-only <see cref="ComboBox" /> control that is bound to the column's bindings.
        /// </summary>
        /// <param name="cell">The cell that will contain the generated element.</param>
        /// <param name="dataItem">The data item represented by the row that contains the intended cell.</param>
        /// <returns>A new, read-only <see cref="ComboBox" /> control that is bound to the column.</returns>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var comboBox = CreateComboBox(isEditing: false);

            ApplyColumnProperties(comboBox);

            if (dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                ApplyBindings(comboBox);
            }

            return comboBox;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        /// <param name="editingElement">The element that the column displays for a cell in editing mode.</param>
        /// <param name="editingEventArgs">Information about the user gesture that is causing a cell to enter editing mode.</param>
        /// <returns>The unedited value. </returns>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is ComboBox comboBox)
            {
                var originalValue = GetCurrentValue(comboBox);

                if (IsDropDownOpeningInput(editingEventArgs))
                {
                    comboBox.IsDropDownOpen = true;
                }

                return originalValue;
            }

            return null;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element is ComboBox comboBox)
            {
                switch (propertyName)
                {
                    case nameof(ItemsSource):
                        DataGridHelper.SyncColumnProperty(this, comboBox, ItemsSourceProperty);
                        break;
                    case nameof(ItemTemplate):
                        DataGridHelper.SyncColumnProperty(this, comboBox, ItemTemplateProperty);
                        break;
                    case nameof(HorizontalContentAlignment):
                        DataGridHelper.SyncColumnProperty(this, comboBox, HorizontalContentAlignmentProperty);
                        break;
                    case nameof(VerticalContentAlignment):
                        DataGridHelper.SyncColumnProperty(this, comboBox, VerticalContentAlignmentProperty);
                        break;
                    case nameof(DisplayMemberPath):
                        comboBox.DisplayMemberBinding = CreateDisplayMemberBinding();
                        break;
                    case nameof(SelectedValuePath):
                        comboBox.SelectedValueBinding = CreateSelectedValuePathBinding();
                        break;
                    case nameof(SelectedItemBinding):
                        ApplyBinding(comboBox, ComboBox.SelectedItemProperty, SelectedItemBinding);
                        break;
                    case nameof(SelectedValueBinding):
                        ApplyBinding(comboBox, ComboBox.SelectedValueProperty, SelectedValueBinding);
                        break;
                    case nameof(TextBinding):
                        ApplyBinding(comboBox, ComboBox.TextProperty, TextBinding);
                        break;
                    default:
                        base.RefreshCellContent(element, propertyName);
                        break;
                }
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        /// <inheritdoc />
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == ItemsSourceProperty ||
                change.Property == ItemTemplateProperty ||
                change.Property == IsEditableProperty ||
                change.Property == HorizontalContentAlignmentProperty ||
                change.Property == VerticalContentAlignmentProperty ||
                change.Property == DisplayMemberPathProperty ||
                change.Property == SelectedValuePathProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        private void ApplyBindings(ComboBox comboBox, AvaloniaProperty skipProperty = null)
        {
            if (SelectedItemBinding != null && skipProperty != ComboBox.SelectedItemProperty)
            {
                ApplyBinding(comboBox, ComboBox.SelectedItemProperty, SelectedItemBinding);
            }

            if (SelectedValueBinding != null && skipProperty != ComboBox.SelectedValueProperty)
            {
                ApplyBinding(comboBox, ComboBox.SelectedValueProperty, SelectedValueBinding);
            }

            if (TextBinding != null && skipProperty != ComboBox.TextProperty)
            {
                ApplyBinding(comboBox, ComboBox.TextProperty, TextBinding);
            }
        }

        private void ApplyColumnProperties(ComboBox comboBox)
        {
            DataGridHelper.SyncColumnProperty(this, comboBox, ItemsSourceProperty);
            DataGridHelper.SyncColumnProperty(this, comboBox, ItemTemplateProperty);
            DataGridHelper.SyncColumnProperty(this, comboBox, IsEditableProperty);
            DataGridHelper.SyncColumnProperty(this, comboBox, HorizontalContentAlignmentProperty);
            DataGridHelper.SyncColumnProperty(this, comboBox, VerticalContentAlignmentProperty);
            comboBox.DisplayMemberBinding = CreateDisplayMemberBinding();
            comboBox.SelectedValueBinding = CreateSelectedValuePathBinding();
        }

        private ControlTheme GetComboBoxTheme(bool isEditing) =>
            isEditing ? CellComboBoxTheme : CellComboBoxDisplayTheme;

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }

        private ComboBox CreateComboBox(bool isEditing)
        {
            var comboBox = new ComboBox
            {
                Margin = new Thickness(0),
                HorizontalAlignment = HorizontalAlignment.Stretch,
                VerticalAlignment = VerticalAlignment.Stretch,
                IsHitTestVisible = isEditing,
                Focusable = isEditing
            };

            if (GetComboBoxTheme(isEditing) is { } theme)
            {
                comboBox.Theme = theme;
            }

            if (!isEditing)
            {
                comboBox.IsTabStop = false;
            }

            return comboBox;
        }

        private BindingBase CreateDisplayMemberBinding()
        {
            if (!string.IsNullOrWhiteSpace(DisplayMemberPath))
            {
                return new Binding(DisplayMemberPath);
            }

            return null;
        }

        private BindingBase CreateSelectedValuePathBinding()
        {
            if (!string.IsNullOrWhiteSpace(SelectedValuePath))
            {
                return new Binding(SelectedValuePath);
            }

            return null;
        }

        private object GetCurrentValue(ComboBox comboBox)
        {
            var property = GetEffectiveTargetProperty();
            if (property == ComboBox.TextProperty)
            {
                return comboBox.Text;
            }

            if (property == SelectingItemsControl.SelectedValueProperty)
            {
                return comboBox.SelectedValue;
            }

            return comboBox.SelectedItem;
        }

        private static bool IsDropDownOpeningInput(RoutedEventArgs editingEventArgs)
        {
            if (editingEventArgs is KeyEventArgs keyArgs)
            {
                var isAltDown = keyArgs.KeyModifiers.HasFlag(KeyModifiers.Alt);
                var key = keyArgs.Key;

                return (key == Key.F4 && !isAltDown) ||
                       ((key == Key.Up || key == Key.Down) && isAltDown);
            }

            if (editingEventArgs is PointerPressedEventArgs pointerArgs)
            {
                var properties = pointerArgs.GetCurrentPoint(null).Properties;
                return properties.IsLeftButtonPressed;
            }

            return false;
        }

        private static bool IsOneWayBinding(BindingBase binding)
        {
            if (binding != null)
            {
                var mode = BindingCloneHelper.GetMode(binding);
                return mode == BindingMode.OneWay ||
                       mode == BindingMode.OneTime ||
                       mode == BindingMode.OneWayToSource;
            }

            return false;
        }

        private static BindingBase PrepareBinding(BindingBase binding, bool applyValueConverter)
        {
            if (binding != null)
            {
                var mode = BindingCloneHelper.GetMode(binding);
                if (mode == BindingMode.OneWayToSource)
                {
                    throw new InvalidOperationException("DataGridComboBoxColumn does not support BindingMode.OneWayToSource. Use BindingMode.TwoWay instead.");
                }

                if (mode == BindingMode.Default)
                {
                    BindingCloneHelper.TrySetMode(binding, BindingMode.TwoWay);
                }

                if (applyValueConverter &&
                    BindingCloneHelper.GetConverter(binding) == null &&
                    string.IsNullOrEmpty(BindingCloneHelper.GetStringFormat(binding)))
                {
                    BindingCloneHelper.TrySetConverter(binding, DataGridValueConverter.Instance);
                }
            }

            return binding;
        }

        private void UpdateSortMemberPath(BindingBase binding)
        {
            if (!string.IsNullOrEmpty(SortMemberPath) || binding == null)
            {
                return;
            }

            var bindingPath = GetBindingPath(binding);
            if (!string.IsNullOrEmpty(bindingPath))
            {
                SortMemberPath = bindingPath;
            }
        }

        private static string GetBindingPath(BindingBase binding)
        {
            return BindingCloneHelper.GetPath(binding);
        }

        private static void ApplyBinding(AvaloniaObject target, AvaloniaProperty property, BindingBase binding)
        {
            if (binding == null)
            {
                return;
            }

            target.Bind(property, binding);
        }

        private static ICellEditBinding BindEditingElement(AvaloniaObject target, AvaloniaProperty property, BindingBase binding)
        {
            if (BindingCloneHelper.TryCreateExplicitBinding(binding, out var explicitBinding))
            {
                target.Bind(property, explicitBinding);
                return new ExplicitCellEditBinding(target, property, binding);
            }

            target.Bind(property, binding);
            return new CellEditBinding(target, property, binding);
        }

    }
}
