// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.

#nullable disable

using Avalonia.Collections;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media;
using System;
using System.ComponentModel;
using Avalonia.Data;
using Avalonia.Layout;
using Avalonia.Markup.Xaml.MarkupExtensions;
using Avalonia.Controls.Documents;
using Avalonia.Controls.DataGridHierarchical;
using Avalonia.Controls.Utils;
using Avalonia.Styling;
using System.Globalization;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="T:Avalonia.Controls.DataGrid" /> column that hosts textual content in its cells.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridTextColumn : DataGridBoundColumn,
        IDataGridDrawnCellValueProvider,
        IDataGridDrawnCellValueChangeTracking
    {
        private readonly Lazy<ControlTheme> _cellTextBoxTheme;
        private readonly Lazy<ControlTheme> _cellTextBlockTheme;
        private readonly Lazy<ControlTheme> _directTextCellTheme;
        private readonly Lazy<ControlTheme> _drawingCellTheme;

        /// <summary>
        /// Gets the theme applied to editing <see cref="TextBox" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBoxTheme => GetThemeValue(_cellTextBoxTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="TextBlock" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBlockTheme => GetThemeValue(_cellTextBlockTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="T:Avalonia.Controls.DataGridTextColumn" /> class.
        /// </summary>
        public DataGridTextColumn()
        {
            BindingTarget = TextBox.TextProperty;

            _cellTextBoxTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellTextBoxTheme"));
            _cellTextBlockTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellTextBlockTheme"));
            _directTextCellTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridOptimizedDirectTextCellTheme"));
            _drawingCellTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridOptimizedDrawingCellTheme"));
        }

        /// <summary>
        /// Defines the <see cref="UseDirectTextCell"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> UseDirectTextCellProperty =
            AvaloniaProperty.Register<DataGridTextColumn, bool>(nameof(UseDirectTextCell));

        /// <summary>
        /// Gets or sets whether display cells use a retained direct-value text template instead of a nested content presenter.
        /// Editing continues to use the normal retained editor template.
        /// </summary>
        public bool UseDirectTextCell
        {
            get => GetValue(UseDirectTextCellProperty);
            set => SetValue(UseDirectTextCellProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="UseDirectTextContent"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> UseDirectTextContentProperty =
            AvaloniaProperty.Register<DataGridTextColumn, bool>(nameof(UseDirectTextContent));

        /// <summary>
        /// Gets or sets whether an ordinary retained <see cref="DataGridCell"/> and its
        /// template-driven text element read compatible typed accessors directly. This keeps
        /// the normal Avalonia layout/content path while avoiding a binding expression per cell.
        /// </summary>
        public bool UseDirectTextContent
        {
            get => GetValue(UseDirectTextContentProperty);
            set => SetValue(UseDirectTextContentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="TrackDirectTextValueChanges"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> TrackDirectTextValueChangesProperty =
            AvaloniaProperty.Register<DataGridTextColumn, bool>(nameof(TrackDirectTextValueChanges), true);

        /// <summary>
        /// Gets or sets whether direct retained text cells subscribe to property changes on their
        /// row data and wrapped hierarchy item. Disable this for immutable row data to avoid the
        /// subscription cost; recycled cells still refresh when their data context changes.
        /// </summary>
        public bool TrackDirectTextValueChanges
        {
            get => GetValue(TrackDirectTextValueChangesProperty);
            set => SetValue(TrackDirectTextValueChangesProperty, value);
        }

        internal bool CanUseDirectValueAccessor =>
            BindingCloneHelper.SupportsDirectTextDataContextRead(Binding) &&
            DataGridColumnMetadata.GetValueAccessor(this) is IDataGridColumnTextAccessor;

        internal bool CanUseDirectValueAccessorFor(object item)
        {
            var accessor = DataGridColumnMetadata.GetValueAccessor(this);
            return BindingCloneHelper.SupportsDirectTextDataContextRead(Binding, item is IHierarchicalNodeItem) &&
                   item != null &&
                   accessor != null &&
                   accessor is IDataGridColumnTextAccessor &&
                   accessor.ItemType.IsInstanceOfType(item);
        }

        /// <summary>
        /// Identifies the FontFamily dependency property.
        /// </summary>
        public static readonly AttachedProperty<FontFamily> FontFamilyProperty =
            TextElement.FontFamilyProperty.AddOwner<DataGridTextColumn>();

        /// <summary>
        /// Gets or sets the font name.
        /// </summary>
        public FontFamily FontFamily
        {
            get => GetValue(FontFamilyProperty);
            set => SetValue(FontFamilyProperty, value);
        }

        /// <summary>
        /// Identifies the FontSize dependency property.
        /// </summary>
        public static readonly AttachedProperty<double> FontSizeProperty =
            TextElement.FontSizeProperty.AddOwner<DataGridTextColumn>();

        /// <summary>
        /// Gets or sets the font size.
        /// </summary>
        // Use DefaultValue here so undo in the Designer will set this to NaN
        [DefaultValue(double.NaN)]
        public double FontSize
        {
            get => GetValue(FontSizeProperty);
            set => SetValue(FontSizeProperty, value);
        }

        /// <summary>
        /// Identifies the FontStyle dependency property.
        /// </summary>
        public static readonly AttachedProperty<FontStyle> FontStyleProperty =
            TextElement.FontStyleProperty.AddOwner<DataGridTextColumn>();

        /// <summary>
        /// Gets or sets the font style.
        /// </summary>
        public FontStyle FontStyle
        {
            get => GetValue(FontStyleProperty);
            set => SetValue(FontStyleProperty, value);
        }

        /// <summary>
        /// Identifies the FontWeight dependency property.
        /// </summary>
        public static readonly AttachedProperty<FontWeight> FontWeightProperty =
            TextElement.FontWeightProperty.AddOwner<DataGridTextColumn>();

        /// <summary>
        /// Gets or sets the font weight or thickness.
        /// </summary>
        public FontWeight FontWeight
        {
            get => GetValue(FontWeightProperty);
            set => SetValue(FontWeightProperty, value);
        }

        /// <summary>
        /// Identifies the FontStretch dependency property.
        /// </summary>
        public static readonly AttachedProperty<FontStretch> FontStretchProperty =
            TextElement.FontStretchProperty.AddOwner<DataGridTextColumn>();

        /// <summary>
        /// Gets or sets the font weight or thickness.
        /// </summary>
        public FontStretch FontStretch
        {
            get => GetValue(FontStretchProperty);
            set => SetValue(FontStretchProperty, value);
        }

        /// <summary>
        /// Identifies the Foreground dependency property.
        /// </summary>
        public static readonly AttachedProperty<IBrush> ForegroundProperty =
            TextElement.ForegroundProperty.AddOwner<DataGridTextColumn>();

        /// <summary>
        /// Gets or sets a brush that describes the foreground of the column cells.
        /// </summary>
        public IBrush Foreground
        {
            get => GetValue(ForegroundProperty);
            set => SetValue(ForegroundProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Watermark"/> property.
        /// </summary>
        public static readonly StyledProperty<string> WatermarkProperty =
            TextBox.WatermarkProperty.AddOwner<DataGridTextColumn>();

        /// <summary>
        /// Gets or sets the placeholder text displayed when the box is empty.
        /// </summary>
        public string Watermark
        {
            get => GetValue(WatermarkProperty);
            set => SetValue(WatermarkProperty, value);
        }

        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == UseDirectTextCellProperty ||
                change.Property == UseDirectTextContentProperty)
            {
                OwningGrid?.OnColumnDisplayModeChanged(this);
            }
            else if (change.Property == FontFamilyProperty
                || change.Property == FontSizeProperty
                || change.Property == FontStyleProperty
                || change.Property == FontWeightProperty
                || change.Property == ForegroundProperty
                || change.Property == WatermarkProperty
                || change.Property == TrackDirectTextValueChangesProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        /// <param name="editingElement">The element that the column displays for a cell in editing mode.</param>
        /// <param name="uneditedValue">The previous, unedited value in the cell being edited.</param>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is TextBox textBox)
            {
                string uneditedString = uneditedValue as string;
                textBox.Text = uneditedString ?? string.Empty;
            }
        }

        /// <summary>
        /// Gets a <see cref="T:Avalonia.Controls.TextBox" /> control that is bound to the column's <see cref="P:Avalonia.Controls.DataGridBoundColumn.Binding" /> property value.
        /// </summary>
        /// <param name="cell">The cell that will contain the generated element.</param>
        /// <param name="dataItem">The data item represented by the row that contains the intended cell.</param>
        /// <returns>A new <see cref="T:Avalonia.Controls.TextBox" /> control that is bound to the column's <see cref="P:Avalonia.Controls.DataGridBoundColumn.Binding" /> property value.</returns>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            if (cell is DataGridCustomDrawingCell drawingCell)
            {
                drawingCell.ClearBuiltInRenderer();
                drawingCell.Theme = OwningGrid?.CellTheme ?? GetColumnControlTheme(typeof(DataGridCell));
                drawingCell.UseRetainedTemplate();
            }

            if (cell is DataGridDirectTextCell directCell)
            {
                directCell.Theme = OwningGrid?.CellTheme ?? GetColumnControlTheme(typeof(DataGridCell));
            }

            var textBox = new TextBox
            {                
                Name = "CellTextBox"
            };
            if (CellTextBoxTheme is { } theme)
            {
                textBox.Theme = theme;
            }

            SyncProperties(textBox);

            return textBox;
        }
        
        /// <summary>
        /// Gets a read-only <see cref="T:Avalonia.Controls.TextBlock" /> element that is bound to the column's <see cref="P:Avalonia.Controls.DataGridBoundColumn.Binding" /> property value.
        /// </summary>
        /// <param name="cell">The cell that will contain the generated element.</param>
        /// <param name="dataItem">The data item represented by the row that contains the intended cell.</param>
        /// <returns>A new, read-only <see cref="T:Avalonia.Controls.TextBlock" /> element that is bound to the column's <see cref="P:Avalonia.Controls.DataGridBoundColumn.Binding" /> property value.</returns>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            if (cell is DataGridCustomDrawingCell drawingCell)
            {
                drawingCell.BeginDisplayConfiguration();
                try
                {
                    drawingCell.Theme = CellTheme ?? GetThemeValue(_drawingCellTheme);
                    SyncProperties(drawingCell);
                    drawingCell.ClearValue(DataGridCustomDrawingCell.ValueProperty);

                    var accessor = DataGridColumnMetadata.GetValueAccessor(this);
                    if (CanUseDrawnValueAccessor(accessor, dataItem, out bool observeWrappedItemValueChanges))
                    {
                        drawingCell.ConfigureBuiltInRenderer(this, renderer: null, observeWrappedItemValueChanges: observeWrappedItemValueChanges);
                    }
                    else
                    {
                        drawingCell.ConfigureBuiltInRenderer(valueProvider: null, renderer: null);
                        if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
                        {
                            drawingCell.Bind(DataGridCustomDrawingCell.ValueProperty, CreateDisplayBinding(Binding));
                        }
                    }
                }
                finally
                {
                    drawingCell.EndDisplayConfiguration();
                }

                return null;
            }

            if (cell is DataGridDirectTextCell directCell)
            {
                directCell.Content = null;
                directCell.Theme = CellTheme ?? GetThemeValue(_directTextCellTheme);
                SyncProperties(directCell);
                ConfigureDirectTextCell(directCell, dataItem);

                return null;
            }

            var textBlockElement = new DataGridSearchTextBlock
            {
                Name = "CellTextBlock"
            };
            if (CellTextBlockTheme is { } theme)
            {
                textBlockElement.Theme = theme;
            }

            SyncProperties(textBlockElement);

            if (UseDirectTextContent && CanUseDirectValueAccessorFor(dataItem))
            {
                textBlockElement.ConfigureDirectText(this, dataItem);
            }
            else if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                textBlockElement.Bind(TextBlock.TextProperty, CreateDisplayBinding(Binding));
            }
            return textBlockElement;
        }

        /// <summary>
        /// Called when the cell in the column enters editing mode.
        /// </summary>
        /// <param name="editingElement">The element that the column displays for a cell in editing mode.</param>
        /// <param name="editingEventArgs">Information about the user gesture that is causing a cell to enter editing mode.</param>
        /// <returns>The unedited value. </returns>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is TextBox textBox)
            {
                string uneditedText = textBox.Text ?? String.Empty;
                int len = uneditedText.Length;
                if (editingEventArgs is KeyEventArgs keyEventArgs && keyEventArgs.Key == Key.F2)
                {
                    // Put caret at the end of the text
                    textBox.SelectionStart = len;
                    textBox.SelectionEnd = len;
                }
                else
                {
                    // Select all text
                    textBox.SelectionStart = 0;
                    textBox.SelectionEnd = len;
                    textBox.CaretIndex = len;
                }

                return uneditedText;
            }
            return string.Empty;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be
        /// updated, because a property changed.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is AvaloniaObject content)
            {
                if (propertyName == nameof(FontFamily))
                {
                    DataGridHelper.SyncColumnProperty(this, content, FontFamilyProperty);
                }
                else if (propertyName == nameof(FontSize))
                {
                    DataGridHelper.SyncColumnProperty(this, content, FontSizeProperty);
                }
                else if (propertyName == nameof(FontStyle))
                {
                    DataGridHelper.SyncColumnProperty(this, content, FontStyleProperty);
                }
                else if (propertyName == nameof(FontWeight))
                {
                    DataGridHelper.SyncColumnProperty(this, content, FontWeightProperty);
                }
                else if (propertyName == nameof(Foreground))
                {
                    DataGridHelper.SyncColumnProperty(this, content, ForegroundProperty);
                }
                else if (propertyName == nameof(Watermark) && content is TextBox textBox)
                {
                    SyncEditingProperties(textBox);
                }
                else if (propertyName == nameof(TrackDirectTextValueChanges) &&
                         content is DataGridDirectTextCell directTextCell)
                {
                    ConfigureDirectTextCell(
                        directTextCell,
                        directTextCell.DataContext,
                        preserveCompatibleMode: true);
                }
                else if (propertyName == nameof(TrackDirectTextValueChanges) &&
                         content is DataGridSearchTextBlock retainedTextBlock)
                {
                    retainedTextBlock.ConfigureDirectText(this, retainedTextBlock.DataContext);
                }
                else if (propertyName == nameof(TrackDirectTextValueChanges) &&
                         content is DataGridCustomDrawingCell drawingCell)
                {
                    drawingCell.RefreshValueProviderSubscription();
                }
            }
            else
            {
                throw DataGridError.DataGrid.ValueIsNotAnInstanceOf("element", typeof(AvaloniaObject));
            }
        }

        internal override DataGridCell CreateCell()
        {
            if (UsesDrawnDisplay)
            {
                return new DataGridCustomDrawingCell();
            }

            return UseDirectTextCell ? new DataGridDirectTextCell() : base.CreateCell();
        }

        internal void ConfigureDirectTextCell(
            DataGridDirectTextCell cell,
            object dataItem,
            bool preserveCompatibleMode = false)
        {
            var useDirectAccessor = CanUseDirectValueAccessorFor(dataItem);
            var resetValueSource = !preserveCompatibleMode ||
                                   !cell.ValueAccessorConfigurationInitialized ||
                                   cell.UsesValueAccessor != useDirectAccessor;
            if (resetValueSource)
            {
                cell.ClearValue(DataGridDirectTextCell.ValueProperty);
            }

            if (!cell.ConfigureValueAccessor(this, dataItem) &&
                resetValueSource &&
                Binding != null &&
                dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                cell.Bind(DataGridDirectTextCell.ValueProperty, CreateDisplayBinding(Binding));
            }
        }

        internal override bool CanReuseCellContentOnDataContextChange =>
            GetType() == typeof(DataGridTextColumn);

        internal override ControlTheme ResolveCellTheme(DataGrid grid)
        {
            return UsesDrawnDisplay
                ? CellTheme ?? GetThemeValue(_drawingCellTheme) ?? base.ResolveCellTheme(grid)
                : UseDirectTextCell
                ? CellTheme ?? GetThemeValue(_directTextCellTheme) ?? base.ResolveCellTheme(grid)
                : base.ResolveCellTheme(grid);
        }

        internal override bool SupportsDrawnDisplay => true;

        object IDataGridDrawnCellValueProvider.GetDrawnCellValue(object item) => GetDirectCellText(item);

        bool IDataGridDrawnCellValueChangeTracking.TrackDrawnCellValueChanges => TrackDirectTextValueChanges;

        internal string GetDirectCellText(object item)
        {
            var accessor = DataGridColumnMetadata.GetValueAccessor(this) as IDataGridColumnTextAccessor;
            if (accessor == null || item == null)
            {
                return null;
            }

            var culture = BindingCloneHelper.GetConverterCulture(Binding) ?? CultureInfo.CurrentCulture;
            return accessor.TryGetText(
                item,
                BindingCloneHelper.GetConverter(Binding),
                BindingCloneHelper.GetConverterParameter(Binding),
                BindingCloneHelper.GetStringFormat(Binding),
                culture,
                culture,
                out var text)
                ? text
                : null;
        }

        private bool CanUseDrawnValueAccessor(IDataGridColumnValueAccessor accessor, object dataItem, out bool observeWrappedItemValueChanges)
        {
            observeWrappedItemValueChanges = false;
            return accessor is IDataGridColumnTextAccessor &&
                   dataItem != null &&
                   accessor.ItemType.IsInstanceOfType(dataItem) &&
                   BindingCloneHelper.SupportsDirectTextDataContextRead(Binding, dataItem is IHierarchicalNodeItem, out observeWrappedItemValueChanges);
        }

        private void SyncProperties(AvaloniaObject content)
        {
            DataGridHelper.SyncColumnProperty(this, content, FontFamilyProperty);
            DataGridHelper.SyncColumnProperty(this, content, FontSizeProperty);
            DataGridHelper.SyncColumnProperty(this, content, FontStyleProperty);
            DataGridHelper.SyncColumnProperty(this, content, FontWeightProperty);
            DataGridHelper.SyncColumnProperty(this, content, ForegroundProperty);

            if (content is TextBox textBox)
            {
                SyncEditingProperties(textBox);
            }
        }

        private void SyncEditingProperties(TextBox textBox)
        {
            if (!string.IsNullOrEmpty(Watermark))
            {
                textBox.Watermark = Watermark;
            }
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }

        private static BindingBase CreateDisplayBinding(BindingBase binding)
        {
            return binding switch
            {
                Binding avaloniaBinding => new Binding
                {
                    Path = avaloniaBinding.Path,
                    ElementName = avaloniaBinding.ElementName,
                    RelativeSource = avaloniaBinding.RelativeSource,
                    Source = avaloniaBinding.Source,
                    TypeResolver = avaloniaBinding.TypeResolver,
                    Delay = avaloniaBinding.Delay,
                    Converter = avaloniaBinding.Converter,
                    ConverterCulture = avaloniaBinding.ConverterCulture,
                    ConverterParameter = avaloniaBinding.ConverterParameter,
                    FallbackValue = avaloniaBinding.FallbackValue,
                    TargetNullValue = avaloniaBinding.TargetNullValue,
                    Priority = avaloniaBinding.Priority,
                    StringFormat = avaloniaBinding.StringFormat,
                    DefaultAnchor = avaloniaBinding.DefaultAnchor,
                    NameScope = avaloniaBinding.NameScope,
                    UpdateSourceTrigger = avaloniaBinding.UpdateSourceTrigger,
                    Mode = GetDisplayMode(avaloniaBinding.Mode)
                },
                CompiledBindingExtension compiledBinding => new CompiledBindingExtension
                {
                    Path = compiledBinding.Path,
                    Delay = compiledBinding.Delay,
                    Converter = compiledBinding.Converter,
                    ConverterCulture = compiledBinding.ConverterCulture,
                    ConverterParameter = compiledBinding.ConverterParameter,
                    FallbackValue = compiledBinding.FallbackValue,
                    TargetNullValue = compiledBinding.TargetNullValue,
                    Priority = compiledBinding.Priority,
                    StringFormat = compiledBinding.StringFormat,
                    Source = compiledBinding.Source,
                    DataType = compiledBinding.DataType,
                    DefaultAnchor = compiledBinding.DefaultAnchor,
                    NameScope = compiledBinding.NameScope,
                    UpdateSourceTrigger = compiledBinding.UpdateSourceTrigger,
                    Mode = GetDisplayMode(compiledBinding.Mode)
                },
                _ => binding
            };
        }

        private static BindingMode GetDisplayMode(BindingMode mode)
        {
            return mode == BindingMode.OneTime ? BindingMode.OneTime : BindingMode.OneWay;
        }
    }
}
