// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using System.Collections.Specialized;
using Avalonia.Collections;
using Avalonia.Controls.Templates;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="ToggleSwitch" /> controls 
    /// for editing boolean values with a toggle switch.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridToggleSwitchColumn : DataGridBoundColumn
    {
        private ToggleSwitch _currentToggleSwitch;
        private DataGrid _owningGrid;
        private readonly Lazy<ControlTheme> _cellToggleSwitchTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="ToggleSwitch" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellToggleSwitchTheme => GetThemeValue(_cellToggleSwitchTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridToggleSwitchColumn"/> class.
        /// </summary>
        public DataGridToggleSwitchColumn()
        {
            BindingTarget = ToggleSwitch.IsCheckedProperty;
            _cellToggleSwitchTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellToggleSwitchTheme"));
        }

        /// <summary>
        /// Defines the <see cref="OnContent"/> property.
        /// </summary>
        public static readonly StyledProperty<object> OnContentProperty =
            ToggleSwitch.OnContentProperty.AddOwner<DataGridToggleSwitchColumn>();

        /// <summary>
        /// Gets or sets the content shown when the switch is on.
        /// </summary>
        public object OnContent
        {
            get => GetValue(OnContentProperty);
            set => SetValue(OnContentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="OffContent"/> property.
        /// </summary>
        public static readonly StyledProperty<object> OffContentProperty =
            ToggleSwitch.OffContentProperty.AddOwner<DataGridToggleSwitchColumn>();

        /// <summary>
        /// Gets or sets the content shown when the switch is off.
        /// </summary>
        public object OffContent
        {
            get => GetValue(OffContentProperty);
            set => SetValue(OffContentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="OnContentTemplate"/> property.
        /// </summary>
        public static readonly StyledProperty<IDataTemplate> OnContentTemplateProperty =
            ToggleSwitch.OnContentTemplateProperty.AddOwner<DataGridToggleSwitchColumn>();

        /// <summary>
        /// Gets or sets the template for on content.
        /// </summary>
        public IDataTemplate OnContentTemplate
        {
            get => GetValue(OnContentTemplateProperty);
            set => SetValue(OnContentTemplateProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="OffContentTemplate"/> property.
        /// </summary>
        public static readonly StyledProperty<IDataTemplate> OffContentTemplateProperty =
            ToggleSwitch.OffContentTemplateProperty.AddOwner<DataGridToggleSwitchColumn>();

        /// <summary>
        /// Gets or sets the template for off content.
        /// </summary>
        public IDataTemplate OffContentTemplate
        {
            get => GetValue(OffContentTemplateProperty);
            set => SetValue(OffContentTemplateProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="IsThreeState"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> IsThreeStateProperty =
            ToggleSwitch.IsThreeStateProperty.AddOwner<DataGridToggleSwitchColumn>();

        /// <summary>
        /// Gets or sets whether three states are supported (nullable bool).
        /// </summary>
        public bool IsThreeState
        {
            get => GetValue(IsThreeStateProperty);
            set => SetValue(IsThreeStateProperty, value);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == OnContentProperty
                || change.Property == OffContentProperty
                || change.Property == OnContentTemplateProperty
                || change.Property == OffContentTemplateProperty
                || change.Property == IsThreeStateProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is ToggleSwitch toggleSwitch)
            {
                toggleSwitch.IsChecked = (bool?)uneditedValue;
            }
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            var toggleSwitch = new ToggleSwitch
            {
                Margin = new Thickness(0)
            };

            if (CellToggleSwitchTheme is { } theme)
            {
                toggleSwitch.Theme = theme;
            }

            ConfigureToggleSwitch(toggleSwitch);
            return toggleSwitch;
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            bool isEnabled = false;
            var toggleSwitch = new ToggleSwitch();

            if (CellToggleSwitchTheme is { } theme)
            {
                toggleSwitch.Theme = theme;
            }

            if (EnsureOwningGrid())
            {
                if (cell.RowIndex != -1 && cell.ColumnIndex != -1 &&
                    cell.OwningRow != null &&
                    cell.OwningRow.Slot == this.OwningGrid.CurrentSlot &&
                    cell.ColumnIndex == this.OwningGrid.CurrentColumnIndex)
                {
                    isEnabled = true;
                    if (_currentToggleSwitch != null)
                    {
                        _currentToggleSwitch.IsEnabled = false;
                    }
                    _currentToggleSwitch = toggleSwitch;
                }
            }

            toggleSwitch.IsEnabled = isEnabled;
            toggleSwitch.IsHitTestVisible = false;
            ConfigureToggleSwitch(toggleSwitch);

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                toggleSwitch.Bind(BindingTarget, Binding);
            }

            return toggleSwitch;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is ToggleSwitch toggleSwitch)
            {
                void EditValue()
                {
                    if (toggleSwitch.IsThreeState)
                    {
                        switch (toggleSwitch.IsChecked)
                        {
                            case false:
                                toggleSwitch.IsChecked = true;
                                break;
                            case true:
                                toggleSwitch.IsChecked = null;
                                break;
                            case null:
                                toggleSwitch.IsChecked = false;
                                break;
                        }
                    }
                    else
                    {
                        toggleSwitch.IsChecked = !toggleSwitch.IsChecked;
                    }
                }

                bool? uneditedValue = toggleSwitch.IsChecked;

                if (editingEventArgs is PointerPressedEventArgs args)
                {
                    void ProcessPointerArgs()
                    {
                        Point position = args.GetPosition(toggleSwitch);
                        Rect rect = new Rect(0, 0, toggleSwitch.Bounds.Width, toggleSwitch.Bounds.Height);
                        if (rect.Contains(position))
                        {
                            EditValue();
                        }
                    }

                    void OnLayoutUpdated(object sender, EventArgs e)
                    {
                        if (toggleSwitch.Bounds.Width != 0 || toggleSwitch.Bounds.Height != 0)
                        {
                            toggleSwitch.LayoutUpdated -= OnLayoutUpdated;
                            ProcessPointerArgs();
                        }
                    }

                    if (toggleSwitch.Bounds.Width == 0 && toggleSwitch.Bounds.Height == 0)
                    {
                        toggleSwitch.LayoutUpdated += OnLayoutUpdated;
                    }
                    else
                    {
                        ProcessPointerArgs();
                    }
                }

                return uneditedValue;
            }

            return false;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is ToggleSwitch toggleSwitch)
            {
                ConfigureToggleSwitch(toggleSwitch);
            }
            else
            {
                throw DataGridError.DataGrid.ValueIsNotAnInstanceOf("element", typeof(ToggleSwitch));
            }
        }

        private void Columns_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.Action == NotifyCollectionChangedAction.Remove && e.OldItems.Contains(this) && _owningGrid != null)
            {
                _owningGrid.ColumnsInternal.CollectionChanged -= Columns_CollectionChanged;
                _owningGrid.CurrentCellChanged -= OwningGrid_CurrentCellChanged;
                _owningGrid.KeyDown -= OwningGrid_KeyDown;
                _owningGrid.LoadingRow -= OwningGrid_LoadingRow;
                _owningGrid = null;
            }
        }

        private void ConfigureToggleSwitch(ToggleSwitch toggleSwitch)
        {
            toggleSwitch.HorizontalAlignment = HorizontalAlignment.Center;
            toggleSwitch.VerticalAlignment = VerticalAlignment.Center;

            if (OnContent != null)
            {
                toggleSwitch.OnContent = OnContent;
            }

            if (OffContent != null)
            {
                toggleSwitch.OffContent = OffContent;
            }

            if (OnContentTemplate != null)
            {
                toggleSwitch.OnContentTemplate = OnContentTemplate;
            }

            if (OffContentTemplate != null)
            {
                toggleSwitch.OffContentTemplate = OffContentTemplate;
            }

            toggleSwitch.IsThreeState = IsThreeState;
        }

        internal override void ClearElementCache()
        {
            base.ClearElementCache();
            _currentToggleSwitch = null;
            if (_owningGrid != null)
            {
                _owningGrid.ColumnsInternal.CollectionChanged -= Columns_CollectionChanged;
                _owningGrid.CurrentCellChanged -= OwningGrid_CurrentCellChanged;
                _owningGrid.KeyDown -= OwningGrid_KeyDown;
                _owningGrid.LoadingRow -= OwningGrid_LoadingRow;
                _owningGrid = null;
            }
        }

        private bool EnsureOwningGrid()
        {
            if (OwningGrid != null)
            {
                if (OwningGrid != _owningGrid)
                {
                    _owningGrid = OwningGrid;
                    _owningGrid.ColumnsInternal.CollectionChanged += Columns_CollectionChanged;
                    _owningGrid.CurrentCellChanged += OwningGrid_CurrentCellChanged;
                    _owningGrid.KeyDown += OwningGrid_KeyDown;
                    _owningGrid.LoadingRow += OwningGrid_LoadingRow;
                }
                return true;
            }
            return false;
        }

        private void OwningGrid_CurrentCellChanged(object sender, DataGridCurrentCellChangedEventArgs e)
        {
            if (_currentToggleSwitch != null)
            {
                _currentToggleSwitch.IsEnabled = false;
            }

            if (OwningGrid != null && OwningGrid.CurrentColumn == this 
                && OwningGrid.IsSlotVisible(OwningGrid.CurrentSlot))
            {
                if (OwningGrid.DisplayData.GetDisplayedElement(OwningGrid.CurrentSlot) is DataGridRow row)
                {
                    ToggleSwitch toggleSwitch = GetCellContent(row) as ToggleSwitch;
                    if (toggleSwitch != null)
                    {
                        toggleSwitch.IsEnabled = true;
                    }
                    _currentToggleSwitch = toggleSwitch;
                }
            }
        }

        private void OwningGrid_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Space && OwningGrid.CurrentColumn == this)
            {
                if (_currentToggleSwitch != null && _currentToggleSwitch.IsEnabled)
                {
                    if (_currentToggleSwitch.IsThreeState)
                    {
                        switch (_currentToggleSwitch.IsChecked)
                        {
                            case false:
                                _currentToggleSwitch.IsChecked = true;
                                break;
                            case true:
                                _currentToggleSwitch.IsChecked = null;
                                break;
                            case null:
                                _currentToggleSwitch.IsChecked = false;
                                break;
                        }
                    }
                    else
                    {
                        _currentToggleSwitch.IsChecked = !_currentToggleSwitch.IsChecked;
                    }
                    e.Handled = true;
                }
            }
        }

        private void OwningGrid_LoadingRow(object sender, DataGridRowEventArgs e)
        {
            if (e.Row.Slot == OwningGrid.CurrentSlot)
            {
                var cell = e.Row.Cells[Index];
                if (cell.Content is ToggleSwitch toggleSwitch)
                {
                    toggleSwitch.IsEnabled = true;
                    _currentToggleSwitch = toggleSwitch;
                }
            }
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
