// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using System.Windows.Input;
using Avalonia.Collections;
using Avalonia.Controls.Templates;
using Avalonia.Controls.Utils;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="Button" /> controls 
    /// for triggering actions (e.g., Delete, Edit, View) per row.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridButtonColumn : DataGridColumn
    {
        private readonly Lazy<ControlTheme> _cellButtonTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="Button" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellButtonTheme => GetThemeValue(_cellButtonTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridButtonColumn"/> class.
        /// </summary>
        public DataGridButtonColumn()
        {
            _cellButtonTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellButtonTheme"));
            IsReadOnly = true; // Buttons don't have an editable value
        }

        /// <summary>
        /// Defines the <see cref="Content"/> property.
        /// </summary>
        public static readonly StyledProperty<object> ContentProperty =
            ContentControl.ContentProperty.AddOwner<DataGridButtonColumn>();

        /// <summary>
        /// Gets or sets the content displayed on the button.
        /// </summary>
        [AssignBinding]
        public object Content
        {
            get => GetValue(ContentProperty);
            set => SetValue(ContentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ContentTemplate"/> property.
        /// </summary>
        public static readonly StyledProperty<IDataTemplate> ContentTemplateProperty =
            ContentControl.ContentTemplateProperty.AddOwner<DataGridButtonColumn>();

        /// <summary>
        /// Gets or sets the template for the button content.
        /// </summary>
        public IDataTemplate ContentTemplate
        {
            get => GetValue(ContentTemplateProperty);
            set => SetValue(ContentTemplateProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Command"/> property.
        /// </summary>
        public static readonly StyledProperty<ICommand> CommandProperty =
            Button.CommandProperty.AddOwner<DataGridButtonColumn>();

        /// <summary>
        /// Gets or sets the command to execute when the button is clicked.
        /// </summary>
        public ICommand Command
        {
            get => GetValue(CommandProperty);
            set => SetValue(CommandProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="CommandParameter"/> property.
        /// </summary>
        public static readonly StyledProperty<object> CommandParameterProperty =
            Button.CommandParameterProperty.AddOwner<DataGridButtonColumn>();

        /// <summary>
        /// Gets or sets the command parameter. If not set, the row's DataContext is used.
        /// </summary>
        [AssignBinding]
        public object CommandParameter
        {
            get => GetValue(CommandParameterProperty);
            set => SetValue(CommandParameterProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ClickMode"/> property.
        /// </summary>
        public static readonly StyledProperty<ClickMode> ClickModeProperty =
            Button.ClickModeProperty.AddOwner<DataGridButtonColumn>();

        /// <summary>
        /// Gets or sets how the button responds to clicks.
        /// </summary>
        public ClickMode ClickMode
        {
            get => GetValue(ClickModeProperty);
            set => SetValue(ClickModeProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="HotKey"/> property.
        /// </summary>
        public static readonly StyledProperty<KeyGesture> HotKeyProperty =
            Button.HotKeyProperty.AddOwner<DataGridButtonColumn>();

        /// <summary>
        /// Gets or sets the keyboard shortcut for the button.
        /// </summary>
        public KeyGesture HotKey
        {
            get => GetValue(HotKeyProperty);
            set => SetValue(HotKeyProperty, value);
        }

        /// <summary>
        /// Gets whether this column is read-only. Always returns true for button columns.
        /// </summary>
        public override bool IsReadOnly
        {
            get => true;
            set { } // Ignore - button columns are always read-only
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == ContentProperty
                || change.Property == ContentTemplateProperty
                || change.Property == CommandProperty
                || change.Property == CommandParameterProperty
                || change.Property == ClickModeProperty
                || change.Property == HotKeyProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Not supported for button columns.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            // Button columns have no editable value
        }

        /// <summary>
        /// Creates the visual tree for cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            var button = new Button
            {
                Name = "CellButton",
                HorizontalAlignment = HorizontalAlignment.Center,
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellButtonTheme is { } theme)
            {
                button.Theme = theme;
            }

            ConfigureButton(button, dataItem);

            return button;
        }

        /// <summary>
        /// Button columns do not support editing - returns the display element.
        /// </summary>
        protected override Control GenerateEditingElement(DataGridCell cell, object dataItem, out ICellEditBinding editBinding)
        {
            editBinding = null;
            return GenerateElement(cell, dataItem);
        }

        /// <summary>
        /// Not supported for button columns.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            return null;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is Button button)
            {
                var dataItem = button.DataContext;
                ConfigureButton(button, dataItem);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private void ConfigureButton(Button button, object dataItem)
        {
            ApplyValueOrBinding(button, ContentControl.ContentProperty, Content, fallbackValue: null);

            if (ContentTemplate != null)
            {
                button.ContentTemplate = ContentTemplate;
            }
            else
            {
                button.ClearValue(ContentControl.ContentTemplateProperty);
            }

            if (Command != null)
            {
                button.Command = Command;
            }
            else
            {
                button.ClearValue(Button.CommandProperty);
            }

            // Use explicit CommandParameter if set, otherwise use the row's data item.
            ApplyValueOrBinding(button, Button.CommandParameterProperty, CommandParameter, dataItem);

            button.ClickMode = ClickMode;

            if (HotKey != null)
            {
                button.HotKey = HotKey;
            }
            else
            {
                button.ClearValue(Button.HotKeyProperty);
            }
        }

        private static void ApplyValueOrBinding(
            AvaloniaObject target,
            AvaloniaProperty property,
            object value,
            object fallbackValue)
        {
            target.ClearValue(property);

            if (value is BindingBase binding)
            {
                ApplyBinding(target, property, binding);
                return;
            }

            var resolvedValue = value ?? fallbackValue;
            if (resolvedValue != null)
            {
                target.SetValue(property, resolvedValue);
            }
        }

        private static void ApplyBinding(AvaloniaObject target, AvaloniaProperty property, BindingBase binding)
        {
            if (binding == null)
            {
                return;
            }

            target.Bind(property, binding);
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
