// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.

using System;

namespace Avalonia.Controls
{
    /// <summary>
    /// Used to specify action to take out of edit mode.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridEditAction
    {
        /// <summary>
        /// Cancel the changes.
        /// </summary>
        Cancel,

        /// <summary>
        /// Commit edited value.
        /// </summary>
        Commit
    }

    // Determines the location and visibility of the editing row.
    internal enum DataGridEditingRowLocation
    {
        Bottom = 0, // The editing row is collapsed below the displayed rows
        Inline = 1, // The editing row is visible and displayed
        Top = 2     // The editing row is collapsed above the displayed rows
    }

    /// <summary>
    /// Determines whether the inner cells' vertical/horizontal gridlines are shown or not.
    /// </summary>
    [Flags]
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridGridLinesVisibility
    {
        None = 0,
        Horizontal = 1,
        Vertical = 2,
        All = 3,
    }

#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridEditingUnit
    {
        Cell = 0,
        Row = 1,
    }

    /// <summary>
    /// Controls which user gestures can begin editing.
    /// </summary>
    [Flags]
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridEditTriggers
    {
        None = 0,
        CellClick = 1 << 0,
        CellDoubleClick = 1 << 1,
        TextInput = 1 << 2,
        F2 = 1 << 3,
        Default = CellClick | F2
    }

    /// <summary>
    /// Determines whether the row/column headers are shown or not.
    /// </summary>
    [Flags]
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridHeadersVisibility
    {
        /// <summary>
        /// Show Row, Column, and Corner Headers
        /// </summary>
        All = Row | Column,

        /// <summary>
        /// Show only Column Headers with top-right corner Header
        /// </summary>
        Column = 0x01,

        /// <summary>
        /// Show only Row Headers with bottom-left corner
        /// </summary>
        Row = 0x02,

        /// <summary>
        /// Don’t show any Headers
        /// </summary>
        None = 0x00
    }

#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridRowDetailsVisibilityMode
    {
        Collapsed = 2,          // Show no details.  Developer is in charge of toggling visibility.
        Visible = 1,	        // Show the details section for all rows.
        VisibleWhenSelected = 0	// Show the details section only for the selected row(s).
    }

    /// <summary>
    /// Determines the type of action to take when selecting items
    /// </summary>
    internal enum DataGridSelectionAction
    {
        AddCurrentToSelection,
        None,
        RemoveCurrentFromSelection,
        SelectCurrent,
        SelectFromAnchorToCurrent
    }

    /// <summary>
    /// Determines the selection model
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridSelectionMode
    {
        Extended = 0,
        Single = 1
    }

#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum DataGridSelectionUnit
    {
        FullRow = 0,
        Cell = 1,
        CellOrRowHeader = 2,
    }

    /// <summary>
    /// Determines how a bound columns source synchronizes with the grid.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum ColumnsSynchronizationMode
    {
        /// <summary>
        /// Changes in the source flow to the grid; grid structural changes do not mutate the source.
        /// </summary>
        OneWayToGrid = 0,

        /// <summary>
        /// Structural changes in the grid are mirrored back to the bound source when supported.
        /// </summary>
        TwoWay = 1
    }

    /// <summary>
    /// Specifies how the grid reacts to Reset notifications from the bound columns source.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum ColumnsSourceResetBehavior
    {
        /// <summary>
        /// Rebuild columns from the source when a reset notification is raised.
        /// </summary>
        Reload = 0,

        /// <summary>
        /// Ignore reset notifications (useful for sources that raise spurious resets).
        /// </summary>
        Ignore = 1
    }

    /// <summary>
    /// Controls placement of auto-generated columns relative to bound columns.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    enum AutoGeneratedColumnsPlacement
    {
        /// <summary>
        /// Auto-generated columns are appended after bound columns.
        /// </summary>
        AfterSource = 0,

        /// <summary>
        /// Auto-generated columns are inserted before bound columns.
        /// </summary>
        BeforeSource = 1,

        /// <summary>
        /// Auto-generation is suppressed when a columns source is set.
        /// </summary>
        None = 2
    }
}
