// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Data;
using System.Linq;
using System.Reflection;
using Avalonia.Data;
using Avalonia.Controls.Utils;

namespace Avalonia.Controls
{
    #if !DATAGRID_INTERNAL
    public
    #else
    internal
    #endif
    partial class DataGrid
    {

        private void AutoGenerateColumnsPrivate()
        {
            if (!_measured || (_autoGeneratingColumnOperationCount > 0))
            {
                // Reading the DataType when we generate columns could cause the CollectionView to
                // raise a Reset if its Enumeration changed.  In that case, we don't want to generate again.
                return;
            }

            using var activity = DataGridDiagnostics.AutoGenerateColumns();
            using var _ = DataGridDiagnostics.BeginColumnsAutoGenerate();
            activity?.SetTag(DataGridDiagnostics.Tags.Columns, ColumnsInternal.Count);

            _autoGeneratingColumnOperationCount++;
            try
            {
                if (_boundColumns != null && AutoGeneratedColumnsPlacement == AutoGeneratedColumnsPlacement.None)
                {
                    RemoveAutoGeneratedColumns();
                    return;
                }

                // Always remove existing autogenerated columns before generating new ones
                RemoveAutoGeneratedColumns();
                GenerateColumnsFromProperties();
                EnsureRowsPresenterVisibility();
                InvalidateRowHeightEstimate();

                if (_boundColumns != null)
                {
                    ApplyAutoGeneratedColumnsPlacement();
                }

                var autoGeneratedCount = 0;
                foreach (var column in ColumnsInternal)
                {
                    if (column.IsAutoGenerated)
                    {
                        autoGeneratedCount++;
                    }
                }

                activity?.SetTag(DataGridDiagnostics.Tags.AutoGeneratedColumns, autoGeneratedCount);
                DataGridDiagnostics.RecordColumnsAutoGenerated(autoGeneratedCount);
                AutoGeneratedColumns?.Invoke(this, EventArgs.Empty);
            }
            finally
            {
                _autoGeneratingColumnOperationCount--;
                if (_autoGeneratingColumnOperationCount == 0)
                {
                    ApplyPendingBoundColumns();
                }
            }
        }



        private void GenerateColumnsFromProperties()
        {
            // Autogenerated Columns are added at the end so the user columns appear first
            var descriptors = DataConnection.DataDescriptors;
            if (descriptors != null && descriptors.Length > 0)
            {
                GenerateColumnsFromDescriptors(descriptors);
            }
            else if (DataConnection.DataProperties != null && DataConnection.DataProperties.Length > 0)
            {
                List<KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs>> columnOrderPairs = new List<KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs>>();

                // Generate the columns
                foreach (PropertyInfo propertyInfo in DataConnection.DataProperties)
                {
                    string columnHeader = propertyInfo.Name;
                    int columnOrder = DATAGRID_defaultColumnDisplayOrder;

                    // Check if DisplayAttribute is defined on the property
                    object[] attributes = propertyInfo.GetCustomAttributes(typeof(DisplayAttribute), true);
                    if (attributes != null && attributes.Length > 0)
                    {
                        DisplayAttribute displayAttribute = attributes[0] as DisplayAttribute;
                        Debug.Assert(displayAttribute != null);

                        bool? autoGenerateField = displayAttribute.GetAutoGenerateField();
                        if (autoGenerateField.HasValue && autoGenerateField.Value == false)
                        {
                            // Abort column generation because we aren't supposed to auto-generate this field
                            continue;
                        }

                        string header = displayAttribute.GetShortName();
                        if (header != null)
                        {
                            columnHeader = header;
                        }

                        int? order = displayAttribute.GetOrder();
                        if (order.HasValue)
                        {
                            columnOrder = order.Value;
                        }
                    }

                    // Generate a single column and determine its relative order
                    int insertIndex = 0;
                    if (columnOrder == int.MaxValue)
                    {
                        insertIndex = columnOrderPairs.Count;
                    }
                    else
                    {
                        foreach (KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs> columnOrderPair in columnOrderPairs)
                        {
                            if (columnOrderPair.Key > columnOrder)
                            {
                                break;
                            }
                            insertIndex++;
                        }
                    }
                    var descriptor = TryGetPropertyDescriptor(propertyInfo);
                    DataGridAutoGeneratingColumnEventArgs columnArgs = GenerateColumn(propertyInfo.PropertyType, propertyInfo.Name, propertyInfo.Name, columnHeader, descriptor);
                    columnOrderPairs.Insert(insertIndex, new KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs>(columnOrder, columnArgs));
                }

                // Add the columns to the DataGrid in the correct order
                foreach (KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs> columnOrderPair in columnOrderPairs)
                {
                    AddGeneratedColumn(columnOrderPair.Value);
                }
            }
            else if (DataConnection.DataIsPrimitive)
            {
                AddGeneratedColumn(GenerateColumn(DataConnection.DataType, string.Empty, string.Empty, DataConnection.DataType.Name));
            }
        }

        private void GenerateColumnsFromDescriptors(DataGridItemPropertyDescriptor[] descriptors)
        {
            var columnOrderPairs = new List<KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs>>();
            var dataRowViewSkipNames = new[] { "Row", "RowVersion", "IsEdit", "IsNew", "HasErrors", "RowError", "Item" };

            foreach (var descriptor in descriptors)
            {
                if (descriptor.PropertyDescriptor != null &&
                    descriptor.PropertyDescriptor.ComponentType == typeof(DataRowView) &&
                    dataRowViewSkipNames.Contains(descriptor.Name))
                {
                    continue;
                }

                string columnHeader = descriptor.DisplayName ?? descriptor.Name;
                int columnOrder = DATAGRID_defaultColumnDisplayOrder;

                DisplayAttribute displayAttribute = null;
                if (descriptor.PropertyInfo != null)
                {
                    var attributes = descriptor.PropertyInfo.GetCustomAttributes(typeof(DisplayAttribute), true);
                    if (attributes != null && attributes.Length > 0)
                    {
                        displayAttribute = attributes[0] as DisplayAttribute;
                    }
                }
                else if (descriptor.PropertyDescriptor != null)
                {
                    displayAttribute = descriptor.PropertyDescriptor.Attributes[typeof(DisplayAttribute)] as DisplayAttribute;
                }

                if (displayAttribute != null)
                {
                    bool? autoGenerateField = displayAttribute.GetAutoGenerateField();
                    if (autoGenerateField.HasValue && autoGenerateField.Value == false)
                    {
                        continue;
                    }

                    string header = displayAttribute.GetShortName();
                    if (header != null)
                    {
                        columnHeader = header;
                    }

                    int? order = displayAttribute.GetOrder();
                    if (order.HasValue)
                    {
                        columnOrder = order.Value;
                    }
                }

                int insertIndex = 0;
                if (columnOrder == int.MaxValue)
                {
                    insertIndex = columnOrderPairs.Count;
                }
                else
                {
                    foreach (KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs> columnOrderPair in columnOrderPairs)
                    {
                        if (columnOrderPair.Key > columnOrder)
                        {
                            break;
                        }
                        insertIndex++;
                    }
                }

                var bindingPath = GetBindingPath(descriptor.Name);
                var propertyDescriptor = descriptor.PropertyDescriptor ?? TryGetPropertyDescriptor(descriptor.PropertyInfo);
                var columnArgs = GenerateColumn(descriptor.PropertyType, descriptor.Name, bindingPath, columnHeader ?? descriptor.PropertyType.Name, propertyDescriptor);
                columnOrderPairs.Insert(insertIndex, new KeyValuePair<int, DataGridAutoGeneratingColumnEventArgs>(columnOrder, columnArgs));
            }

            foreach (var columnOrderPair in columnOrderPairs)
            {
                AddGeneratedColumn(columnOrderPair.Value);
            }
        }

        private static string GetBindingPath(string propertyName)
        {
            if (string.IsNullOrEmpty(propertyName))
            {
                return propertyName;
            }

            if (propertyName.Length > 1 &&
                propertyName[0] == TypeHelper.LeftIndexerToken &&
                propertyName[propertyName.Length - 1] == TypeHelper.RightIndexerToken)
            {
                return propertyName;
            }

            bool requiresIndexer = false;
            foreach (var ch in propertyName)
            {
                if (!char.IsLetterOrDigit(ch) && ch != '_')
                {
                    requiresIndexer = true;
                    break;
                }
            }

            if (requiresIndexer)
            {
                return $"{TypeHelper.LeftIndexerToken}{propertyName}{TypeHelper.RightIndexerToken}";
            }

            return propertyName;
        }



        private static DataGridAutoGeneratingColumnEventArgs GenerateColumn(Type propertyType, string propertyName, string bindingPath, string header, PropertyDescriptor propertyDescriptor = null)
        {
            var newColumn = CreateDataGridColumnFromType(propertyType, bindingPath);
            newColumn.Header = header;
            newColumn.IsAutoGenerated = true;
            var args = new DataGridAutoGeneratingColumnEventArgs(propertyName, propertyType, newColumn)
            {
                PropertyDescriptor = propertyDescriptor
            };
            return args;
        }

        private static PropertyDescriptor TryGetPropertyDescriptor(PropertyInfo propertyInfo)
        {
            if (propertyInfo == null)
            {
                return null;
            }

            try
            {
                var declaringType = propertyInfo.DeclaringType ?? propertyInfo.ReflectedType;
                if (declaringType == null)
                {
                    return null;
                }

                return TypeDescriptor.GetProperties(declaringType)[propertyInfo.Name];
            }
            catch
            {
                return null;
            }
        }



        private bool AddGeneratedColumn(DataGridAutoGeneratingColumnEventArgs e)
        {
            // Raise the AutoGeneratingColumn event in case the user wants to Cancel or Replace the
            // column being generated
            OnAutoGeneratingColumn(e);
            if (e.Cancel)
            {
                return false;
            }
            else
            {
                if (e.Column != null)
                {
                    // Set the IsAutoGenerated flag here in case the user provides a custom autogenerated column
                    e.Column.IsAutoGenerated = true;
                }
                ColumnsInternal.Add(e.Column);
                ColumnsInternal.AutogeneratedColumnCount++;
                return true;
            }
        }



        private static DataGridColumn CreateDataGridColumnFromType(Type type, string bindingPath)
        {
            Debug.Assert(type != null);

            var nullableType = Nullable.GetUnderlyingType(type);
            var coreType = nullableType ?? type;

            // Booleans -> CheckBox column
            if (coreType == typeof(bool))
            {
                return new DataGridCheckBoxColumn
                {
                    Binding = new Binding(bindingPath),
                    IsThreeState = nullableType != null
                };
            }

            // Enums -> ComboBox column
            if (coreType.IsEnum)
            {
                return new DataGridComboBoxColumn
                {
                    ItemsSource = Enum.GetValues(coreType),
                    SelectedItemBinding = new Binding(bindingPath)
                };
            }

            // Uri -> Hyperlink column
            if (coreType == typeof(Uri))
            {
                var hyperlinkBinding = new Binding(bindingPath);
                return new DataGridHyperlinkColumn
                {
                    Binding = hyperlinkBinding,
                    ContentBinding = new Binding(bindingPath)
                    {
                        Converter = DataGridValueConverter.Instance
                    }
                };
            }

            // Fallback -> text column
            return new DataGridTextColumn
            {
                Binding = new Binding(bindingPath)
            };
        }



        private void RemoveAutoGeneratedColumns()
        {
            int index = 0;
            _autoGeneratingColumnOperationCount++;
            try
            {
                while (index < ColumnsInternal.Count)
                {
                    // Skip over the user columns
                    while (index < ColumnsInternal.Count && !ColumnsInternal[index].IsAutoGenerated)
                    {
                        index++;
                    }
                    // Remove the autogenerated columns
                    while (index < ColumnsInternal.Count && ColumnsInternal[index].IsAutoGenerated)
                    {
                        ColumnsInternal.RemoveAt(index);
                    }
                }
                ColumnsInternal.AutogeneratedColumnCount = 0;
            }
            finally
            {
                _autoGeneratingColumnOperationCount--;
            }
        }


    }
}
